// ── Static event data ─────────────────────────────────────────────────────────
// Single source of truth for all curated/static events.
// Both the main site (js/script.js) and admin portal (admin/admin.js) read from
// this array so every event is rendered by the same function and is visible in
// the admin portal.
//
// Fields mirror the Firestore event schema used by handleFormSubmit():
//   title, description, type, day, weekend, region, venue, time, url, img, pick
//
// The admin "Import drafts" button imports any unimported events here into
// Firestore so they can be edited and managed via the admin interface.
// ─────────────────────────────────────────────────────────────────────────────
const STATIC_EVENTS = [
  // ── 28 Feb – 1 Mar 2026 ──────────────────────────────────────────────────
  {
    title: 'Wellington Art Show 2026',
    type: 'culture', day: 'sat', weekend: '2026-02-28', region: 'wellington',
    time: 'Sat 10:00 am – 8:00 pm (runs 27 Feb–1 Mar)',
    venue: 'Tākina Convention Centre, 50 Cable St',
    description: 'Thousands of original works across painting, ceramics, jewellery, textiles and sculpture, plus live artist demonstrations. Kids under 16 free with a paying adult.',
    url: 'https://www.wellingtonartshow.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Trapezegallery.jpg',
    pick: true,
  
    label: '🎨 Art Show',
    labelStyle: 'color:#5B4A8A',
    ticketed: true,
    family: 'Family',
    cost: 'Weekend pass $10 · Under 16s free with adult',},
  {
    title: '20 Summers Fest — Home Alone Records',
    type: 'music', day: 'sat', weekend: '2026-02-28', region: 'wellington',
    time: 'Doors 1:00 pm · Gig from 1:15 pm',
    venue: 'Central Wellington (venue TBA)',
    description: 'Home Alone Records celebrates 20 years with 10+ acts including French for Rabbits, Lake South and Young Moon. All ages, tamariki under 12 free — a genuinely special afternoon of NZ music.',
    url: 'https://www.eventfinda.co.nz/whatson/events/wellington',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Chris_Ellis_music_340_%2851501975643%29.jpg/960px-Chris_Ellis_music_340_%2851501975643%29.jpg',
    pick: true,
  
    label: '🎶 Live Music',
    labelStyle: 'color:#7A3B8A',
    family: 'All Ages',
    cost: 'Children under 12 free',},
  {
    title: 'NZ Festival of the Arts 2026',
    type: 'culture', day: 'sat', weekend: '2026-02-28', region: 'wellington',
    time: '24 Feb – 15 Mar · Multiple sessions daily',
    venue: 'Wellington CBD — multiple venues',
    description: 'The 40th anniversary edition of NZ\'s premier arts festival — dance, music, theatre and free whānau zones with face-painting and storytelling. Free street performances at Civic Square all weekend.',
    url: 'https://www.festival.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Arts_Festival_Premiere_Weekend_%2826707354691%29.jpg/960px-Arts_Festival_Premiere_Weekend_%2826707354691%29.jpg',
    pick: true,
  
    label: '🎨 Arts Festival',
    labelStyle: 'color:#5B4A8A',
    family: 'All Ages',
    cost: 'Mix of free & ticketed',},
  {
    title: 'Wellington Art Show — Final Day',
    type: 'culture', day: 'sun', weekend: '2026-02-28', region: 'wellington',
    time: 'Sunday 10:00 am – 5:00 pm',
    venue: 'Tākina Convention Centre, 50 Cable St',
    description: 'Last chance to explore hundreds of original NZ artworks before the show closes. Live artist demonstrations and a beautiful gallery atmosphere at Tākina.',
    url: 'https://www.wellingtonartshow.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Trapezegallery.jpg',
    pick: false,
  
    label: '🎨 Art Show',
    labelStyle: 'color:#5B4A8A',
    ticketed: true,
    family: 'Family',
    cost: 'Weekend pass $10 · Under 16s free with adult',},
  {
    title: 'NZ Fringe Festival 2026',
    type: 'culture', day: 'sun', weekend: '2026-02-28', region: 'wellington',
    time: 'Running until 7 March · Various times',
    venue: 'Multiple venues across Wellington',
    description: '178 shows across theatre, comedy, dance, circus and interactive performance. whānau-friendly showcases throughout — check the programme for family picks this weekend.',
    url: 'https://www.fringe.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/WPG_Fringe_2018.jpg/960px-WPG_Fringe_2018.jpg',
    pick: false,
  
    label: '🎭 Fringe Festival',
    labelStyle: 'color:#5B4A8A',
    free: 'Some free',
    family: 'Family',},

  // ── 7–8 Mar 2026 ─────────────────────────────────────────────────────────
  {
    title: 'Martinborough Fair 2026',
    type: 'festival', day: 'sat', weekend: '2026-03-07', region: 'wairarapa',
    time: 'Saturday 8:00 am – 4:00 pm',
    venue: 'Martinborough Square, Martinborough',
    description: 'Nearly 500 stalls of handmade goods, jewellery, pottery, woodwork, clothing, plants and street food. Live music, big bubbles, face painting and all proceeds to local charities. A proper day out — worth the drive over the hill.',
    url: 'https://www.eventfinda.co.nz/2026/martinborough-fair/martinborough',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/NZ-Martinborough.jpg/960px-NZ-Martinborough.jpg',
    pick: true,
  
    label: '🎪 Street Fair',
    labelStyle: 'color:#C8901A',
    free: 'Free entry',
    family: 'Family',},
  {
    title: 'Wellington Pride Parade 2026',
    type: 'festival', day: 'sat', weekend: '2026-03-07', region: 'wellington',
    time: 'Saturday 5:30 pm – 7:00 pm',
    venue: 'Courtenay Place & Dixon Street, Te Aro',
    description: 'Wellington\'s iconic Pride Parade — music, performers, DJs and a joyful community atmosphere. An inclusive celebration welcoming all whānau to watch or march. Part of Wellington Pride Festival 6–22 March.',
    url: 'https://www.wellingtonpridefestival.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GayPrideParade.jpg/960px-GayPrideParade.jpg',
    pick: true,
  
    label: '🌈 Pride Parade',
    labelStyle: 'color:#8b4bcc',
    stripStyle: 'background:linear-gradient(90deg,#e74c8b,#f0a030,#3ab065,#2980b9,#8b4bcc)',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Wellington Tramway Museum — Ride the Trams',
    type: 'outdoor', day: 'sun', weekend: '2026-03-07', region: 'kapiti',
    time: 'Sundays 11:00 am – 4:30 pm',
    venue: 'Queen Elizabeth Park, Paekakariki',
    description: 'Ride historic Wellington trams through beautiful Queen Elizabeth Park to the beach. Kids adore this — a true Wellington treasure delighting families for decades.',
    url: 'https://www.wellingtontrams.org.nz',
    img: '',
    pick: false,
  
    label: '🚂 Heritage Trams',
    labelStyle: 'color:#1A8A6E',
    family: 'Family',
    cost: 'Small fee',},
  {
    title: 'Newtown Festival',
    type: 'festival', day: 'sun', weekend: '2026-03-07', region: 'wellington',
    time: 'Sunday 8 March · 12pm – 6pm',
    venue: 'Riddiford St, Newtown, Wellington',
    description: 'Wellington\'s most beloved free community festival — live music on multiple stages, street food, stalls and arts celebrating Newtown\'s vibrant community. A genuine Wellington institution, perfect for all ages.',
    url: 'https://www.newtownfestival.org.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Newtown_Festival_2017.jpg/960px-Newtown_Festival_2017.jpg',
    pick: true,
  
    label: '🎪 Community Festival',
    labelStyle: 'color:#E8610A',
    free: 'Free',
    family: 'Family',},

  // ── 14–15 Mar 2026 ───────────────────────────────────────────────────────
  {
    title: 'Wellington Waterfront Parkrun',
    type: 'outdoor', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: 'Saturday 8:00 am (briefing 7:45 am)',
    venue: 'Frank Kitts Park, Wellington Waterfront',
    description: 'Free weekly 5km run/walk along Wellington\'s beautiful waterfront. All paces welcome — register once at parkrun.co.nz and run anywhere in the world forever.',
    url: 'https://www.parkrun.co.nz/wellington/',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Bushy_parkrun_27th_September_2014_%2815194006519%29.jpg/960px-Bushy_parkrun_27th_September_2014_%2815194006519%29.jpg',
    pick: false,
  
    label: '🏃 Parkrun',
    labelStyle: 'color:#1A8A6E',
    free: 'Free',
    family: 'All Ages',},
  {
    title: 'Wellington Phoenix Double Header',
    type: 'outdoor', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: 'Saturday 14 March · Check Ticketek for times',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'A rare A-League double header — two Phoenix games at Hnry Stadium on the same day. The Phoenix are pushing for finals football and home games have electric atmosphere. Great live sport for families — bring a scarf and your voice.',
    url: 'https://www.wellingtonphoenix.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Crowd_at_WPX_vs_MBV_game_on_26_August_2007.jpg',
    pick: true,
  
    label: '⚽ A-League · Double Header',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — premier.ticketek.co.nz',},
  {
    title: 'NZ Festival of the Arts — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: '14–15 March · Last chance weekend',
    venue: 'Wellington CBD — multiple venues',
    description: 'Final weekend of NZ\'s premier arts festival — don\'t miss your last chance to catch world-class performances, free Civic Square street acts and the whānau zones. Unmissable Wellington event.',
    url: 'https://www.festival.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Spiky_performance_%2814775440009%29.jpg/960px-Spiky_performance_%2814775440009%29.jpg',
    pick: true,
  
    label: '🎨 Arts Festival',
    labelStyle: 'color:#5B4A8A',
    family: 'All Ages',
    cost: 'Mix of free & ticketed',},
  {
    title: 'Wellington Lantern Festival — Year of the Horse',
    type: 'festival', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: 'Thu 12 – Sun 15 Mar · Nightly from 4 pm, until 10 pm Fri–Sun',
    venue: 'Wellington Botanic Garden Ki Paekākā',
    description: 'A magical journey of lights through the Botanic Garden — from the main gate up Pinehill Path, through the Herb Garden, and down through the Lady Norwood Rose Garden and the Dell. Hundreds of lanterns, live performances on the Dell Stage, and festive atmosphere for the whole whānau.',
    url: 'https://www.facebook.com/events/701959832589342/',
    img: 'https://upload.wikimedia.org/wikipedia/commons/3/36/China-Shanghai-YuGarden-the_Lantern_Festival-2012_1828.JPG',
    pick: true,
    label: '🏮 Lantern Festival',
    labelStyle: 'color:#C8901A',
    free: 'Free entry',
    family: 'All Ages',},
  {
    title: 'Out in the City — Pride Family Fair',
    type: 'festival', day: 'sun', weekend: '2026-03-14', region: 'wellington',
    time: 'Sunday — all day (check wellingtonpridefestival.com)',
    venue: 'Odlins Plaza, Wellington Waterfront',
    description: 'Wellington Pride Festival\'s free all-ages family fair — live performances, food stalls, activities for tamariki and a joyful inclusive atmosphere on the waterfront. Part of Wellington Pride Festival 6–22 March.',
    url: 'https://www.wellingtonpridefestival.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GayPrideParade.jpg/960px-GayPrideParade.jpg',
    pick: true,
  
    label: '🌈 Pride Festival',
    labelStyle: 'color:#8b4bcc',
    stripStyle: 'background:linear-gradient(90deg,#e74c8b,#f0a030,#3ab065,#2980b9,#8b4bcc)',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Te Matapihi ki te Ao Nui — Wellington Library Opening Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: '14–15 March · Opening celebration',
    venue: 'Te Matapihi ki te Ao Nui / Te Ngākau Civic Square, Wellington CBD',
    description: 'The grand reopening of Wellington Central Library and Te Ngākau Civic Square — explore new community spaces, exhibitions and events across the weekend. A celebration for the whole whānau. Free entry.',
    url: 'https://wellington.govt.nz/news-and-events/events-and-festivals',
    img: '',
    pick: true,

    label: '📚 Free · Grand Opening',
    labelStyle: 'color:#1A5E8A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Ōtaki International Kite Festival',
    type: 'festival', day: 'sat', weekend: '2026-03-14', region: 'kapiti',
    time: '10:00 am – 4:00 pm',
    venue: 'Ōtaki Beach, Kāpiti Coast',
    description: 'Free annual kite festival with NZ Kite Association fliers — watch spectacular kites fill the sky above the beach. Hands-on fun for all ages.',
    url: 'https://kapiticoast.govt.nz/explore-kapiti/things-to-do-in-kapiti/whats-on/events-in-kapiti/',
    img: '',
    pick: false,

    label: '🪁 Free Festival',
    labelStyle: 'color:#2478A8',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Kapiti Classic 2026',
    type: 'music', day: 'sat', weekend: '2026-03-14', region: 'kapiti',
    time: '11:00 am – 7:00 pm',
    venue: 'Kāpiti Coast (venue TBC)',
    description: 'Summer music festival celebrating nostalgic New Zealand acts — a day of classic Kiwi music and good vibes on the Kāpiti Coast.',
    url: 'https://kapiticoast.govt.nz/explore-kapiti/things-to-do-in-kapiti/whats-on/events-in-kapiti/',
    img: '',
    pick: false,

    label: '🎶 Music Festival',
    labelStyle: 'color:#7A3B8A',
    cost: 'Ticketed',},

  // ── 21–22 Mar 2026 ───────────────────────────────────────────────────────
  {
    title: 'Hutt City Autumn Festival',
    type: 'outdoor', day: 'sat', weekend: '2026-03-21', region: 'lower-hutt',
    time: 'Saturday 10:00 am – 4:00 pm',
    venue: 'Riddiford Gardens, Lower Hutt',
    description: 'Riddiford Gardens bursts into colour in autumn — a beautiful park full of mature trees turning gold and red. Bring a picnic, let the kids loose on the grass and enjoy the seasonal colours at their peak.',
    url: 'https://www.lowerhutt.govt.nz/parks-recreation',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Lower_Hutt_2024_aerial_shot.jpg/960px-Lower_Hutt_2024_aerial_shot.jpg',
    pick: false,
  
    label: '🌸 Festival',
    labelStyle: 'color:#1A8A6E',
    free: 'Free',
    family: 'Family',},
  {
    title: 'St Patrick\'s Day Parade & Festival on the Waterfront',
    type: 'festival', day: 'sun', weekend: '2026-03-21', region: 'wellington',
    time: 'Sunday 1:00 pm – 4:30 pm',
    venue: 'Queens Wharf, Wellington Waterfront',
    description: 'Wellington\'s beloved St Patrick\'s Day celebration — a colourful parade through the city followed by a free festival on the waterfront with live Irish music, dancing, food and family entertainment. A fantastic free afternoon out for all ages.',
    url: 'https://www.eventfinda.co.nz/whatson/events/wellington',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Wellington_Harbour%2C_New_Zealand%2C_Nov._2009.jpg/960px-Wellington_Harbour%2C_New_Zealand%2C_Nov._2009.jpg',
    pick: true,
  
    label: '☘️ St Patrick\'s Day',
    labelStyle: 'color:#1A6A2A',
    stripStyle: 'background:linear-gradient(90deg,#1A6A2A,#2eaa44)',
    free: 'Free',
    family: 'All Ages',},
  {
    title: 'NZ Blackcaps v South Africa — T20 International',
    type: 'outdoor', day: 'sun', weekend: '2026-03-21', region: 'wellington',
    time: 'Sunday 22 March · Check tickets for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'The Blackcaps take on South Africa in a T20 at Hnry Stadium. T20 is the most family-friendly cricket format — fast, exciting and done in about three hours. The stadium\'s covered stands and waterfront location make it a brilliant day out.',
    url: 'https://www.tickets.nzc.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Cricket_test_at_Basin_Reserve%2C_10-15_February_1978_%2824668812080%29.jpg/960px-Cricket_test_at_Basin_Reserve%2C_10-15_February_1978_%2824668812080%29.jpg',
    pick: true,
  
    label: '🏏 T20 International',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — tickets.nzc.nz',},
  {
    title: 'Boneface Brewing — Sunday Session',
    type: 'outdoor', day: 'sun', weekend: '2026-03-21', region: 'upper-hutt',
    time: 'Sunday from 12:00 pm',
    venue: 'Boneface Brewing, Upper Hutt',
    description: 'Upper Hutt\'s best kept secret — Boneface\'s family-friendly taproom with rotating food trucks and excellent craft beer. Kids are genuinely welcome and well catered for. A perfect Sunday afternoon combining a Hutt Valley drive with a great feed.',
    url: 'https://www.bonefacebrewing.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Oxbow_Collaboration_Part_1_%2833338778230%29.jpg/960px-Oxbow_Collaboration_Part_1_%2833338778230%29.jpg',
    pick: false,
  
    label: '🍺 Brewery',
    labelStyle: 'color:#C8901A',
    family: 'Family',},
  {
    title: 'Karaone Putiputi with The Tīwhas',
    type: 'culture', day: 'sat', weekend: '2026-03-21', region: 'wellington',
    time: 'Check website for time',
    venue: 'Te Matapihi ki te Ao Nui, Te Ngākau Civic Square, Wellington CBD',
    description: 'A Pride celebration at Wellington\'s newly reopened library — make flower crowns (karaone putiputi) and enjoy live performances by The Tīwhas girl group. A joyful, family-friendly afternoon. Free.',
    url: 'https://wellington.govt.nz/news-and-events/event-calendar',
    img: '',
    pick: false,

    label: '🌸 Pride · Family',
    labelStyle: 'color:#8b4bcc',
    free: 'Free',
    family: 'Family',},

  // ── 28–29 Mar 2026 ───────────────────────────────────────────────────────
  {
    title: 'CubaDupa 2026 — Free Street Festival',
    type: 'music', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Sat 28 & Sun 29 March · All day & evening',
    venue: 'Cuba Street & Cuba Quarter, Wellington CBD',
    description: 'NZ\'s largest outdoor arts and music festival — 12 stages, street theatre, LED dragons, Bollywood dancers, samba drummers, circus, food trucks and pop-up art. Completely free for the whole family.',
    url: 'https://www.cubadupa.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Free_Agents_Brass_Band_%40_CubaDupa%2C_March_25%2C_2018_%2839204825960%29.jpg/960px-Free_Agents_Brass_Band_%40_CubaDupa%2C_March_25%2C_2018_%2839204825960%29.jpg',
    pick: true,
  
    label: '🎪 Street Festival',
    labelStyle: 'color:#8A1A1A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Hurricanes v Reds',
    type: 'outdoor', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'The Hurricanes host the Queensland Reds at Hnry Stadium. Wellington\'s home Super Rugby games are always a fantastic atmosphere — the stadium is compact and loud, and the Hurricanes have a history of playing high-octane attacking rugby. Great live sport alongside CubaDupa this weekend.',
    url: 'https://www.hurricanes.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/The_Chiefs_%28Waikato%29_v_The_Hurricanes_%28Wellington%29.jpg/960px-The_Chiefs_%28Waikato%29_v_The_Hurricanes_%28Wellington%29.jpg',
    pick: true,
  
    label: '🌀 Super Rugby',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — hurricanes.flicket.co.nz',},
  {
    title: 'Māoriland Film Festival 2026',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'kapiti',
    time: '24–28 March · 10:00 am – 10:00 pm daily',
    venue: 'Māoriland Hub, 68 Main Street, Ōtaki',
    description: 'The Southern Hemisphere\'s largest indigenous film festival — five days of indigenous cinema from around the world, including NZ premieres and special events. The 2026 theme is "light that reveals our legacies."',
    url: 'https://www.maorilandfilm.co.nz',
    img: '',
    pick: false,

    label: '🎬 Film Festival',
    labelStyle: 'color:#C8390A',
    cost: 'Ticketed — maorilandfilm.co.nz',
    family: 'Family',},
  {
    title: 'Pātaka Art + Museum — IHI & Ongo Exhibition Openings',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'porirua',
    time: '10:00 am – 5:00 pm · Opening events Sat 28 Mar',
    venue: 'Pātaka Art + Museum, cnr Norrie & Parumoana Streets, Porirua',
    description: 'Double exhibition opening at Pātaka — IHI explores inner force through three emerging Māori artists, while Ongo: (Re)sounding the Vā unpacks Pacific sound and space. Opening day includes a free walk-through and live performances. Free admission.',
    url: 'https://pataka.org.nz/whats-on/',
    img: '',
    pick: false,

    label: '🎨 Free Exhibition',
    labelStyle: 'color:#5B4A8A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'The Rocky Horror Show — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Sat 2:30 pm matinee & 7:30 pm · Sun 1:00 pm (final show)',
    venue: 'St James Theatre, 77–87 Courtenay Place, Wellington',
    description: 'The iconic stage musical returns to NZ for the first time in 15 years — direct from the UK with a West End cast. Sweet Transvestite, Time Warp, Dammit Janet. Dress-up warmly encouraged. Final weekend.',
    url: 'https://rockyhorror.co.nz',
    img: '',
    pick: false,

    label: '🎭 Musical Theatre',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed — rockyhorror.co.nz',},
  {
    title: 'Wellington City Orchestra — Louise Webster Violin Concerto',
    type: 'music', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: '3:00 pm – 4:45 pm',
    venue: 'St Andrew\'s on The Terrace, 30 The Terrace, Wellington',
    description: 'Conductor Justus Rozemond leads the orchestra with violinist Helene Pohl. Includes the NZ premiere of Louise Webster\'s violin concerto, Lili Boulanger, and Prokofiev\'s Romeo and Juliet Suite No. 2.',
    url: 'https://events.humanitix.com/wellington-city-orchestra-28-march-2026',
    img: '',
    pick: false,

    label: '🎻 Live Orchestra',
    labelStyle: 'color:#5B4A8A',
    cost: 'From $20 · Children free',},
  {
    title: 'Peach PRC — Wandering Spirit Tour',
    type: 'music', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Doors 7:00 pm · Peach PRC 9:15 pm',
    venue: 'Shed 6, 4 Queens Wharf, Wellington',
    description: 'Australian pop artist Peach PRC headlines her NZ debut — theatrical boundary-pushing pop with 230M+ streams. Support from Sydney artist Salty. Licensed all-ages show on the Wellington waterfront.',
    url: 'https://www.frontiertouring.com/peachprc',
    img: '',
    pick: false,

    label: '🎤 Live Music',
    labelStyle: 'color:#C8390A',
    cost: 'GA $79.90 · VIP $179.90',},
  {
    title: 'The Superlative Artistry of Japan — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'upper-hutt',
    time: 'Gallery hours — check website',
    venue: 'Whirinaki Whare Taonga, 836 Fergusson Drive, Upper Hutt',
    description: 'Free travelling exhibition by the Embassy of Japan — closing this weekend. Captures Japan\'s monozukuri (craft) spirit across traditional kogei, elaborate Meiji-era works, contemporary craft and food art. Free entry.',
    url: 'https://www.expressions.org.nz/exhibitions/current-exhibitions/',
    img: '',
    pick: false,

    label: '🇯🇵 Free Exhibition · Closing',
    labelStyle: 'color:#8A1A1A',
    free: 'Free',
    family: 'Family',},
  // ── 3–6 Apr 2026 (Easter long weekend) ───────────────────────────────────
  {
    title: 'Armageddon Expo — Good Friday Opening Day',
    type: 'festival', day: 'fri', weekend: '2026-04-04', region: 'wellington',
    time: 'Friday 3 April · 10:00 am – 4:00 pm',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Good Friday is Day 1 of Armageddon — NZ\'s biggest pop culture event. The opening day tends to be less crowded than Saturday, making it easier to get to the exhibits, panels and celebrity meet-and-greets. Andy Serkis and Renée O\'Connor are among the guest headliners. Running Friday to Sunday over Easter.',
    url: 'https://www.armageddonexpo.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg/960px-LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg',
    pick: false,

    label: '🤖 Pop Culture Expo · Opens Today',
    labelStyle: 'color:#1A5C99',
    family: 'Family',
    cost: 'Adult $25 · Child (5–12) $14 · Family $69',},
  {
    title: 'Wairarapa Balloon Festival — Good Friday Welcome Flight',
    type: 'outdoor', day: 'fri', weekend: '2026-04-04', region: 'wairarapa',
    time: 'Friday 3 April · 7:00 am – 8:30 am',
    venue: 'Carrington Park, Carterton, Wairarapa',
    description: 'The opening balloon ascension of the Wairarapa Balloon Festival — colourful hot air balloons lift off from Carrington Park as Wairarapa wakes up for Easter. Free to watch, weather-permitting. The festival continues across the Easter long weekend with morning flights and the spectacular Night Glow.',
    url: 'https://wairarapanz.com/products/wairarapa-balloon-festival',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Hot_air_balloons_in_Grass_Valley%2C_CA.jpg/960px-Hot_air_balloons_in_Grass_Valley%2C_CA.jpg',
    pick: true,

    label: '🎈 Balloon Festival · Opens Today',
    labelStyle: 'color:#C8390A',
    free: 'Free to watch',
    family: 'Family',},
  {
    title: 'Armageddon Expo Wellington 2026',
    type: 'festival', day: 'sat', weekend: '2026-04-04', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'TSB Arena, Wellington Waterfront',
    description: 'NZ\'s biggest pop culture event — gaming, anime, comics, cosplay competitions, celebrity meet-and-greets and esports. Guest headliners include Andy Serkis and Renee O\'Connor. Thousands of cosplayers roam the floor. A brilliant Easter weekend outing for kids and big kids alike.',
    url: 'https://www.armageddonexpo.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg/960px-LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg',
    pick: true,
  
    label: '🤖 Pop Culture Expo',
    labelStyle: 'color:#1A5C99',
    family: 'Family',
    cost: 'Ticketed · Family passes available',},
  {
    title: 'White Ferns v South Africa — 3rd ODI',
    type: 'outdoor', day: 'sat', weekend: '2026-04-04', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Basin Reserve, Wellington',
    description: 'The White Ferns face South Africa in the third One Day International at the iconic Basin Reserve. A fantastic live sport experience for families — Wellington\'s most beloved cricket ground with a great atmosphere on a long Easter weekend.',
    url: 'https://www.tickets.nzc.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Basin_Reserve_newzealand.jpg/960px-Basin_Reserve_newzealand.jpg',
    pick: false,
  
    label: '🏏 Women\'s Cricket',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Check Basin Reserve website for tickets',},
  {
    title: 'Armageddon Expo — Easter Sunday',
    type: 'festival', day: 'sun', weekend: '2026-04-04', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'TSB Arena, Wellington Waterfront',
    description: 'Day two of Armageddon — often quieter than Saturday with still-full programming. Great chance for a second pass through the show floor, catching any panels or meet-and-greets you missed. Sunday also tends to have the best cosplay of the weekend.',
    url: 'https://www.armageddonexpo.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg/960px-LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg',
    pick: false,
  
    label: '🤖 Pop Culture Expo',
    labelStyle: 'color:#1A5C99',
    family: 'Family',
    cost: 'Ticketed · Family passes available',},
  {
    title: 'NZ Brass Band National Championships — A & B Grade Finals',
    type: 'culture', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'The pinnacle of New Zealand\'s brass band scene — A and B Grade bands from across the country compete at Michael Fowler Centre. Spectacular ensemble playing in a world-class concert hall. A surprisingly brilliant live music experience for families, with big sound and high drama.',
    url: 'https://www.nzbrass.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: false,

    label: '🎺 Live Music · Competition',
    labelStyle: 'color:#5B4A8A',
    family: 'Family',
    cost: 'Ticketed',},
  {
    title: 'Ride the Cyclone — Circa Theatre',
    type: 'culture', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: 'Various sessions · Runs 11 Apr – 9 May',
    venue: 'Circa Theatre, 1 Taranaki Street, Wellington',
    description: 'The cult Canadian musical about a high school choir who die on a rollercoaster — and must compete for the chance to return to life. Dark, hilarious and wildly inventive, Ride the Cyclone has become a phenomenon through social media. Circa\'s production is a rare NZ staging of one of the most talked-about musicals of recent years. Don\'t miss it.',
    url: 'https://www.circa.co.nz/shows/',
    img: '',
    pick: true,

    label: '🎭 Cult Musical',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — circa.co.nz',},
  {
    title: 'The BIG Easter Weekend at Ngā Manu',
    type: 'kids', day: 'fri', weekend: '2026-04-04', region: 'kapiti',
    time: '3–6 April · 10:00 am – 5:00 pm daily',
    venue: 'Ngā Manu Nature Reserve, Kauri Road, Waikanae',
    description: 'Family Easter fun at Ngā Manu Nature Reserve — Easter egg hunts with $3,000 in prizes among native birds and wildlife. A magical long-weekend adventure in one of Kāpiti\'s finest wildlife sanctuaries.',
    url: 'https://www.ngamanu.org.nz',
    img: '',
    pick: false,

    label: '🐣 Easter · Family',
    labelStyle: 'color:#C8901A',
    family: 'Family',
    cost: 'Entry fee applies',},
  {
    title: 'Wairarapa Balloon Festival — Easter Monday Farewell Flight',
    type: 'outdoor', day: 'mon', weekend: '2026-04-04', region: 'wairarapa',
    time: 'Monday 6 April · 7:00 am – 8:30 am',
    venue: 'Mystery location (announced day before), Wairarapa',
    description: 'The final balloon ascension of the Wairarapa Balloon Festival — traditionally launched from a surprise location announced the evening before. A beautiful way to end the Easter long weekend, watching hot air balloons drift over Wairarapa farmland in the morning light. Free to watch, weather permitting.',
    url: 'https://wairarapanz.com/products/wairarapa-balloon-festival',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Hot_air_balloons_in_Grass_Valley%2C_CA.jpg/960px-Hot_air_balloons_in_Grass_Valley%2C_CA.jpg',
    pick: false,

    label: '🎈 Balloon Festival · Farewell Flight',
    labelStyle: 'color:#C8390A',
    free: 'Free to watch',
    family: 'Family',},
  {
    title: 'Ōtaki Easter Market',
    type: 'market', day: 'sun', weekend: '2026-04-04', region: 'kapiti',
    time: '10:00 am – 2:00 pm',
    venue: 'State Highway 1, Ōtaki (opposite New World)',
    description: 'Special Easter edition of the popular outdoor Ōtaki market — local stallholders, fresh produce, crafts and Easter surprises. A great stop on the way north for the long weekend.',
    url: 'https://kapiticoast.govt.nz/explore-kapiti/things-to-do-in-kapiti/whats-on/events-in-kapiti/',
    img: '',
    pick: false,

    label: '🛒 Easter Market',
    labelStyle: 'color:#1A6B3A',
    free: 'Free entry',
    family: 'Family',},
  {
    title: 'Toi Art Saturdays: Sit and Sketch',
    type: 'culture', day: 'sat', weekend: '2026-04-04', region: 'wellington',
    time: '10:00 am – 1:00 pm',
    venue: 'Toi Art, Te Papa Tongarewa, 55 Cable Street',
    description: 'A free monthly drop-in drawing session inside Te Papa\'s stunning Toi Art gallery. Grab a pencil and spend the morning looking closely at artworks, joining short talks and sketching at your own pace. Open to all ages and skill levels — a calm, creative start to the Easter weekend.',
    url: 'https://www.tepapa.govt.nz/visit/whats-on',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg/960px-Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg',
    pick: false,

    label: '🎨 Free Drop-in',
    labelStyle: 'color:#5B4A8A',
    free: 'Free',
    family: 'Family',},

  // ── 10–13 Apr 2026 ───────────────────────────────────────────────────────
  {
    title: 'Ultra New Zealand 2026',
    type: 'festival', day: 'fri', weekend: '2026-04-11', region: 'wellington',
    time: 'Friday 10 April · All day',
    venue: 'Wellington Waterfront',
    description: 'The inaugural ULTRA Music Festival in New Zealand comes to Wellington — one of the world\'s most iconic electronic music brands landing on the waterfront for the first time. Three main stages plus a dedicated drum and bass stage with artists including The Chainsmokers, DJ Snake, Zedd, Alison Wonderland, Pendulum (DJ Set), Oliver Heldens and more. 20,000+ expected.',
    url: 'https://www.ultranewzealand.com',
    img: '',
    pick: true,

    label: '🎧 Electronic Music Festival',
    labelStyle: 'color:#5B1A8A',
    cost: 'Ticketed — ultranewzealand.com',},
  {
    title: 'K-Pop Live — St James Theatre',
    type: 'music', day: 'mon', weekend: '2026-04-11', region: 'wellington',
    time: 'Monday 13 April · 2:30 pm & 6:00 pm (two shows)',
    venue: 'St James Theatre, 77 Courtenay Place, Wellington',
    description: 'A one-hour live K-pop concert experience — authentic costumes, precision choreography and the biggest hits from BTS, Blackpink, Stray Kids and more. Choreographed by Rina Chae, this is a brilliant school holidays treat for K-pop fans of all ages. Two sessions available — book ahead.',
    url: 'https://www.wellingtonnz.com/visit/events/k-pop-live',
    img: '',
    pick: true,

    label: '🎤 K-Pop Live Show',
    labelStyle: 'color:#8A1A5B',
    family: 'Family',
    cost: 'Ticketed — wellingtonnz.com',},
  {
    title: 'Hurricanes v Blues',
    type: 'outdoor', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Massive Super Rugby rivalry match — the Hurricanes host the Blues at Hnry Stadium. Blues vs Hurricanes is always one of the most electric games of the season. Loud, packed, and brilliant live sport.',
    url: 'https://www.hurricanes.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Hurricanes_vs_Waratahs_2015.jpg/960px-Hurricanes_vs_Waratahs_2015.jpg',
    pick: true,
  
    label: '🌀 Super Rugby',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — hurricanes.flicket.co.nz',},
  {
    title: 'Porirua Grand Traverse',
    type: 'outdoor', day: 'sun', weekend: '2026-04-11', region: 'porirua',
    time: 'Sunday 12 April · From 7:00 am',
    venue: 'Start/Finish: Kai Tahi Foodhall, 20 Parumoana St, Porirua',
    description: 'Wellington\'s biggest multisport festival — choose from a 9km fun run/walk to a full 58km challenge crossing Porirua Harbour, native bush, coastal farmland and hidden trails. Options for all ages and abilities.',
    url: 'https://poriruagrandtraverse.co.nz',
    img: '',
    pick: false,

    label: '🏃 Multisport Festival',
    labelStyle: 'color:#C8390A',
    family: 'Family',
    cost: 'Entry fee — poriruagrandtraverse.co.nz',},
  {
    title: 'HELP! A Monster Ate My Story — Circa Theatre',
    type: 'kids', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: '11:30 am & 1:30 pm (Sat); 1:30 pm & 3:30 pm (Sun)',
    venue: 'Circa Two, 1 Taranaki Street, Wellington',
    description: 'Ruth Paul\'s beloved picture book leaps off the page in this 50-minute musical stage show for children aged 3–9. Lion, Jellyfish, T-Rex and Kiwi team up to stop a mish-mash monster from eating their stories. Runs Tuesday 7 – Sunday 19 April with a relaxed performance (pre-show character meet-and-greet) on Wednesday 15 April at 11:30 am.',
    url: 'https://www.circa.co.nz/shows/',
    img: '',
    pick: true,

    label: '🎭 Kids Theatre',
    labelStyle: 'color:#1A8A6E',
    family: 'Family',
    cost: '$20 per person · $70 family pass (4 tickets)',},
  {
    title: 'Whānau Day: Breathe | Mauri Ora — Te Papa',
    type: 'culture', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: '10:00 am – 2:00 pm',
    venue: 'Te Papa Tongarewa, 55 Cable Street, Wellington',
    description: 'A free family day built around the dazzling Breathe | Mauri Ora digital art exhibition. Explore connections to te taiao through art-making, taonga puoro (Māori musical instruments), and a children\'s discovery trail. NZSL interpreters are available, making it fully accessible for Deaf whānau.',
    url: 'https://www.tepapa.govt.nz/visit/whats-on',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg/960px-Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg',
    pick: false,

    label: '🌿 Free Family Day',
    labelStyle: 'color:#1A8A6E',
    free: 'Free',
    family: 'Family',},

  // ── 18–19 Apr 2026 ───────────────────────────────────────────────────────
  {
    title: 'Brewtown Beer Fest 2026',
    type: 'festival', day: 'sat', weekend: '2026-04-18', region: 'upper-hutt',
    time: '12:00 pm – 6:30 pm',
    venue: 'Brewtown, 16 Miro St, Upper Hutt',
    description: 'Annual craft beer festival at Brewtown Upper Hutt — local and guest breweries, live music and food in the open-air courtyard of Upper Hutt\'s thriving craft beer hub.',
    url: 'https://brewtown.co.nz/beerfest',
    img: '',
    pick: false,

    label: '🍺 Beer Festival',
    labelStyle: 'color:#C8901A',
    cost: 'Ticketed — brewtown.co.nz/beerfest',},
  {
    title: 'NZSO Stories Alive! The Tortoise and the Hare',
    type: 'kids', day: 'sat', weekend: '2026-04-18', region: 'wellington',
    time: '10:30 am & 12:30 pm (both days)',
    venue: 'Te Papa Tongarewa, 55 Cable Street, Wellington',
    description: 'Five NZSO musicians bring the classic fable to life in this lively 45-minute interactive concert designed for young children. Sing, clap, and watch the story unfold through live music and illustration in a perfect first live music experience. Runs Friday 17 and Saturday 18 April — book ahead as sessions fill fast.',
    url: 'https://www.nzso.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg/960px-Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg',
    pick: false,

    label: '🎻 Family Concert',
    labelStyle: 'color:#5B4A8A',
    family: 'Family',
    cost: 'Ticketed — nzso.co.nz',},
  {
    title: 'Orchestra Wellington: Mozart Requiem',
    type: 'music', day: 'sat', weekend: '2026-04-18', region: 'wellington',
    time: '7:30 pm',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'Orpheus Choir Wellington and Orchestra Wellington unite for a breathtaking double bill — Christopher Tin\'s soaring To Shiver the Sky (celebrating humanity\'s dream of flight) paired with Mozart\'s timeless and soul-stirring Requiem. A majestic evening of choral music at Wellington\'s finest concert hall.',
    url: 'https://orchestrawellington.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: false,

    label: '🎶 Choral Concert',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — orchestrawellington.co.nz',},
  {
    title: 'Wellington Saints v Manawatu Jets',
    type: 'outdoor', day: 'sun', weekend: '2026-04-11', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'TSB Arena, Wellington Waterfront',
    description: 'Wellington\'s beloved Saints host Manawatu Jets at TSB Arena in the Sal\'s NBL. Fast, high-energy basketball in a compact arena where every seat is close to the action. Saints games are brilliant family sport — loud, local and always entertaining.',
    url: 'https://www.salsbasketball.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/2019_NCAA_Men%27s_Basketball_Finals_Game_3_crowd.jpg/960px-2019_NCAA_Men%27s_Basketball_Finals_Game_3_crowd.jpg',
    pick: false,
  
    label: '🏀 Sal\'s NBL Basketball',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — saints.co.nz',},

  // ── 24–27 Apr 2026 (ANZAC long weekend) ─────────────────────────────────
  {
    title: 'City Nature Challenge — ANZAC Weekend Bioblitz',
    type: 'outdoor', day: 'fri', weekend: '2026-04-25', region: 'wellington',
    time: 'Friday 24 – Monday 27 April · Anytime',
    venue: 'Wellington region — wherever you find nature',
    description: 'Wellington joins 650+ cities worldwide in the City Nature Challenge — a 4-day bioblitz where anyone can document wild plants, animals and fungi using the free iNaturalist app. No expertise needed: photograph anything alive in a park, garden, beach or bush and it contributes to Wellington\'s tally. Great family activity across the whole ANZAC long weekend. Guided expert walks on Monday 27 April (see below).',
    url: 'https://wellington.govt.nz/climate-change-sustainability-environment/environment/what-you-can-do-for-the-environment/digital-tools-for-nature',
    img: '',
    pick: false,

    label: '🌿 Nature Bioblitz · Free App',
    labelStyle: 'color:#1A6B3A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Faultline Ultra — Wellington Trail Races',
    type: 'outdoor', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: 'Check schedule',
    venue: 'Wellington City Centre & Trail Networks',
    description: 'Epic multi-distance trail running through Wellington\'s best trail networks across the ANZAC long weekend. From a beginner-friendly 6km to a 100-mile monster. The finish line in the city centre is a great free spectator spot to cheer runners home.',
    url: 'https://www.faultlineultra.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Kilian.jpg',
    pick: false,
  
    label: '🏃 Trail Running',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Ticketed · Distances from 6km to 100 miles',},
  {
    title: 'ANZAC Day — Dawn Service & National Ceremony',
    type: 'other', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: '6:00 am dawn service, 11:00 am national ceremony',
    venue: 'Pukeahu, Wellington',
    description: 'Wellington hosts New Zealand\'s national ANZAC Day commemorations. The 6am dawn service at Pukeahu is a deeply moving experience. The 11am National Commemoration Service is broadcast live on TVNZ 1 and RNZ. Also: wreath laying at the Cenotaph, Lambton Quay at 9am. Free and open to all.',
    url: '',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Dawn_service_gnangarra_03.jpg/960px-Dawn_service_gnangarra_03.jpg',
    pick: false,
  
    label: '🌺 National Commemoration',
    labelStyle: 'color:#8A1A00',
    stripStyle: 'background:linear-gradient(90deg,#8A1A00,#c43030)',
    free: 'Free',},
  {
    title: 'Wrights Hill Fortress — ANZAC Day Open Day',
    type: 'culture', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: '10:00 am – 4:00 pm',
    venue: 'Wrights Hill Fortress, 50 Wrights Hill Road, Karori',
    description: 'Explore 620 metres of authentic WWII underground tunnels, gun emplacements and history displays at this remarkable hillside fortress. Volunteer guides lead one-hour tours through the tunnels, or self-guide with a history pamphlet. A genuinely memorable piece of Wellington\'s wartime history — bring a torch and wear comfortable shoes.',
    url: 'https://wrightshillfortress.org.nz',
    img: '',
    pick: false,

    label: '🏰 WWII Fortress',
    labelStyle: 'color:#8A1A00',
    family: 'Family',
    cost: 'Adults $10 · Under 15s $5 · Family $20 (cash only)',},
  {
    title: 'The King of Pop Show',
    type: 'music', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'The Opera House, 111 Manners Street, Wellington',
    description: 'The world\'s most spectacular Michael Jackson tribute — a full live band, authentic costumes, flawless choreography and the complete Michael Jackson songbook from Off the Wall through Dangerous. A high-energy show that has toured internationally for years and thrills audiences of all ages.',
    url: 'https://www.theoperahouse.co.nz',
    img: '',
    pick: false,

    label: '🎤 Tribute Show',
    labelStyle: 'color:#1A1A8A',
    cost: 'Ticketed — theoperahouse.co.nz',},
  {
    title: 'NZ Warriors v Dolphins — ANZAC Day Match',
    type: 'outdoor', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Wellington hosts the prestigious NRL ANZAC Round for the first time — a historic night with the Warriors facing the Dolphins, including a pre-game ANZAC ceremony. Only the fourth time the Warriors have played an ANZAC match on New Zealand soil. A brilliant way to finish ANZAC Day.',
    url: 'https://www.nrl.com.au',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Melbourne_Storm_vs_Dolphins%2C_NRL_2024_Round_25_at_AAMI_Park.jpg/960px-Melbourne_Storm_vs_Dolphins%2C_NRL_2024_Round_25_at_AAMI_Park.jpg',
    pick: true,
  
    label: '🏉 NRL ANZAC Round',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed',},
  {
    title: 'Faultline Ultra — Day Two',
    type: 'outdoor', day: 'sun', weekend: '2026-04-25', region: 'wellington',
    time: 'Check schedule',
    venue: 'Wellington City Centre & Trail Networks',
    description: 'The longer Faultline Ultra distances continue into Sunday — the 53km, 103km and 100-mile runners are still out on course. Head to the city-centre finish zone to cheer them across the line. Free to spectate.',
    url: 'https://www.faultlineultra.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Kilian.jpg',
    pick: false,

    label: '🏃 Trail Running',
    labelStyle: 'color:#1A6B3A',},
  {
    title: 'City Nature Challenge — Island Bay Rock Pool Walk',
    type: 'outdoor', day: 'mon', weekend: '2026-04-25', region: 'wellington',
    time: 'Monday 27 April · 6:00 pm – 8:00 pm',
    venue: 'Taputeranga Marine Reserve, 194 The Esplanade, Island Bay',
    description: 'Explore the rock pools of Island Bay\'s marine reserve with experts from Mountains to Sea Wellington, Te Papa and Wellington City Council. Spot sea stars, crabs, fish and the occasional octopus at low tide. A brilliant whānau activity on the ANZAC Monday public holiday — no experience needed, just curiosity. Part of the global City Nature Challenge bioblitz weekend.',
    url: 'https://www.mountainstoseawellington.org/events',
    img: '',
    pick: true,

    label: '🐙 Guided Rock Pool Walk · Free',
    labelStyle: 'color:#0B5563',
    free: 'Free',
    family: 'Family',},

  // ── 1–4 May 2026 ─────────────────────────────────────────────────────────
  {
    title: 'Toi Art Saturdays: Sit and Sketch',
    type: 'culture', day: 'sat', weekend: '2026-05-02', region: 'wellington',
    time: '10:00 am – 1:00 pm',
    venue: 'Toi Art, Te Papa Tongarewa, 55 Cable Street',
    description: 'The monthly free drop-in drawing session inside Te Papa\'s stunning Toi Art gallery returns for May. Grab a pencil and spend the morning looking closely at artworks, joining short talks and sketching at your own pace. Open to all ages and skill levels.',
    url: 'https://www.tepapa.govt.nz/visit/whats-on',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg/960px-Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg',
    pick: false,

    label: '🎨 Free Drop-in',
    labelStyle: 'color:#5B4A8A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Aqua Nullius: Toe Fai! and Talaucaka — Circa Theatre',
    type: 'culture', day: 'sat', weekend: '2026-05-02', region: 'wellington',
    time: 'Various sessions · Runs 2–16 May',
    venue: 'Circa Theatre, 1 Taranaki Street, Wellington',
    description: 'Two interconnected Pasifika theatre works by Emele Ugavule — blending speculative sci-fi with Indigenous Oceanic storytelling. Set decades apart and linked through the journey of one woman navigating AI, ancestry and colonial power. A Studio Kiin production. Thought-provoking and original.',
    url: 'https://www.circa.co.nz/shows/',
    img: '',
    pick: false,

    label: '🎭 Pasifika Theatre',
    labelStyle: 'color:#1A6B3A',
    cost: '$25–$45 — circa.co.nz',},
  {
    title: 'Hurricanes v Crusaders',
    type: 'outdoor', day: 'fri', weekend: '2026-05-02', region: 'wellington',
    time: 'Friday 1 May · Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Hurricanes host the Crusaders in a massive Super Rugby clash — the great Wellington vs Canterbury rivalry at Hnry Stadium. Kids under 15 go free with a paying adult, making this one of the best-value family sports outings of the season. Book early as this one always sells out.',
    url: 'https://www.hurricanes.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Hurricanes_vs_Waratahs_2015.jpg/960px-Hurricanes_vs_Waratahs_2015.jpg',
    pick: true,

    label: '🌀 Super Rugby · Kids Free',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Kids under 15 free · hurricanes.flicket.co.nz',},
  {
    title: 'Boney M — Final Curtain Tour',
    type: 'music', day: 'fri', weekend: '2026-05-02', region: 'wellington',
    time: 'Friday 1 May · Check schedule for time',
    venue: 'St James Theatre, 77 Courtenay Place, Wellington',
    description: 'The legendary disco icons bring their farewell world tour to Wellington — Ra Ra Rasputin, Rivers of Babylon, Brown Girl in the Ring and more, performed live at the beautifully restored St James Theatre. A guaranteed good time and a chance to see one of the 70s\' greatest acts one final time.',
    url: 'https://www.stjamestheatre.co.nz',
    img: '',
    pick: false,

    label: '🕺 Disco Legends · Farewell Tour',
    labelStyle: 'color:#8A1A8A',
    cost: 'Ticketed — stjamestheatre.co.nz',},
  {
    title: 'Fat Freddy\'s Drop — Based On A True Story (21st Anniversary)',
    type: 'music', day: 'sat', weekend: '2026-05-02', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'Wellington\'s own Fat Freddy\'s Drop perform their landmark debut album in full — Aotearoa\'s longest-charting album (111 weeks in the NZ Top 40). Three consecutive nights in their home city, also a tribute to founding member Chris \'MU\' Faiumu. An unmissable moment for any Wellington music fan.',
    url: 'https://www.fatfreddysdrop.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Fat_Freddys_Drop_Group_Photo.jpg',
    pick: true,
  
    label: '🎸 Live Music · Wellington Icon',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed',},
  {
    title: 'Best Foods Comedy Festival Gala — Opening Night',
    type: 'culture', day: 'sat', weekend: '2026-05-02', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Q Theatre, Wellington',
    description: 'The annual Comedy Festival Gala brings together the best national and international comedians for a single highlight-reel night, hosted by Dai Henwood. The perfect way to sample the festival and decide which full shows to book. Always sells out fast.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: true,
  
    label: '😂 Comedy Gala',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed',},
  {
    title: 'Fat Freddy\'s Drop — Final Night',
    type: 'music', day: 'sun', weekend: '2026-05-02', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'The final night of Fat Freddy\'s Drop\'s three-night homecoming run. Third nights traditionally go hardest — the band relaxed, the crowd knowing every word, and the horns section at full power. A very special send-off for an iconic album.',
    url: 'https://www.fatfreddysdrop.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Fat_Freddys_Drop_Group_Photo.jpg',
    pick: true,
  
    label: '🎸 Live Music',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed',},
  {
    title: 'NZ International Comedy Festival — Weekend Shows',
    type: 'culture', day: 'sat', weekend: '2026-05-09', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'The NZ International Comedy Festival is in full swing — dozens of shows from local legends and international acts across Wellington venues all month. This weekend features Felicity Ward, David Correos and many more. Check the full programme to find your picks.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: false,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},

  // ── 8–11 May 2026 ────────────────────────────────────────────────────────
  {
    title: 'The Pink Floyd Experience — The Wall+',
    type: 'music', day: 'sat', weekend: '2026-05-09', region: 'wellington',
    time: 'Saturday 9 May · 8:00 pm',
    venue: 'TSB Arena, 55 Cable Street, Wellington Waterfront',
    description: 'NZ\'s long-running Pink Floyd tribute brings The Wall to TSB Arena in full theatrical staging — the iconic album performed live with the construction and destruction of the wall set, opening with a set of classic Floyd anthems. An extraordinary sensory experience for any Floyd fan.',
    url: 'https://pinkfloydexperience.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/TSB_Arena_Wellington.jpg/960px-TSB_Arena_Wellington.jpg',
    pick: true,

    label: '🎸 Pink Floyd Tribute · Full Production',
    labelStyle: 'color:#1A1A6A',
    cost: 'Ticketed — pinkfloydexperience.co.nz',},
  {
    title: 'Central Pulse vs Northern Mystics — ANZ Premiership',
    type: 'outdoor', day: 'sat', weekend: '2026-05-09', region: 'porirua',
    time: 'Saturday 9 May · 7:00 pm',
    venue: 'Te Rauparaha Arena, 17 Parumoana St, Porirua',
    description: 'Wellington\'s Central Pulse host the Northern Mystics in the ANZ Premiership — top-flight women\'s netball at its finest. Fast, physical and brilliantly entertaining. Te Rauparaha Arena is a great compact venue where every seat is close to the court. Brilliant value family sport.',
    url: 'https://www.pulse.org.nz',
    img: '',
    pick: false,

    label: '🏐 ANZ Premiership Netball',
    labelStyle: 'color:#8A1A1A',
    family: 'Family',
    cost: 'Ticketed — pulse.org.nz',},
  {
    title: 'NZSL Week: Whānau Fun at Te Papa',
    type: 'culture', day: 'sat', weekend: '2026-05-09', region: 'wellington',
    time: 'Saturday 9 May · 10:00 am – 12:00 pm',
    venue: 'Te Papa Tongarewa, 55 Cable Street, Wellington',
    description: 'Free family activities on Te Papa\'s marae celebrating New Zealand Sign Language Week (4–10 May). Learn signs, explore Deaf culture, and celebrate NZSL as one of Aotearoa\'s three official languages. NZSL interpreters on hand. Open and welcoming for all whānau.',
    url: 'https://www.tepapa.govt.nz/visit/whats-on',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg/960px-Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg',
    pick: false,

    label: '🤟 NZSL Week · Free',
    labelStyle: 'color:#1A6B3A',
    free: 'Free',
    family: 'Family',},
  {
    title: '& Juliet — St James Theatre',
    type: 'culture', day: 'sat', weekend: '2026-05-09', region: 'wellington',
    time: 'Various sessions · Runs 9 May – 24 May',
    venue: 'St James Theatre, 77 Courtenay Place, Wellington',
    description: 'The smash-hit West End and Broadway musical asks: what if Juliet didn\'t die? Packed with anthems by Max Martin — Baby One More Time, Roar, Since U Been Gone, It\'s My Life and more — & Juliet is joyful, funny and wildly entertaining. Fresh from its award-winning London and New York runs, this is its New Zealand premiere.',
    url: 'https://www.stjamestheatre.co.nz',
    img: '',
    pick: true,

    label: '🎭 West End Musical · NZ Premiere',
    labelStyle: 'color:#8A1A5B',
    cost: 'Ticketed — stjamestheatre.co.nz',},
  {
    title: 'Wellington Better Home & Living Show',
    type: 'other', day: 'sat', weekend: '2026-05-09', region: 'wellington',
    time: 'Fri–Sat 10:00 am – 5:00 pm · Sun 10:00 am – 4:00 pm',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Wellington\'s biggest home improvement and lifestyle expo fills Hnry Stadium across the long weekend (Fri 8 – Sun 10 May). Hundreds of exhibitors across kitchens, building, renovation, heating, solar, interior design and more, plus free Ask An Expert presentations throughout. Great for anyone planning a reno or just looking for inspiration.',
    url: 'https://homeandgardenshow.co.nz/event/wellington-better-home-living-show/',
    img: '',
    pick: false,

    label: '🏠 Home & Living Expo',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Ticketed — homeandgardenshow.co.nz',},
  {
    title: 'NZ International Comedy Festival — Sunday Shows',
    type: 'culture', day: 'sun', weekend: '2026-05-09', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'A Comedy Festival show makes a brilliant Mother\'s Day treat — plenty of matinée and evening options this Sunday. Sashi Perera: Pear Tree runs this weekend, along with Ben Knight and David Correos. Check the programme for family-appropriate options.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: false,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},

  // ── 15–18 May 2026 ───────────────────────────────────────────────────────
  {
    title: 'Modern God — Circa Theatre',
    type: 'culture', day: 'fri', weekend: '2026-05-16', region: 'wellington',
    time: 'Various sessions · Runs 15–23 May',
    venue: 'Circa Theatre, 1 Taranaki Street, Wellington',
    description: 'Six social media influencers collide in this high-energy dance-theatre work exploring fame, consumerism and identity. A provocative and visually arresting production from Footnote New Zealand Dance, running across this weekend and the following weekend. Powerful and thought-provoking for older teens and adults.',
    url: 'https://www.circa.co.nz/shows/',
    img: '',
    pick: false,

    label: '💃 Dance Theatre',
    labelStyle: 'color:#8A1A8A',
    cost: 'Ticketed — circa.co.nz',},
  {
    title: 'Central Pulse vs Magic — ANZ Premiership',
    type: 'outdoor', day: 'sun', weekend: '2026-05-16', region: 'wellington',
    time: 'Sunday 17 May · 4:00 pm',
    venue: 'TSB Arena, 55 Cable Street, Wellington Waterfront',
    description: 'Central Pulse host the Waikato Bay of Plenty Magic at the waterfront TSB Arena in the ANZ Premiership. Top-flight women\'s netball in Wellington city — fast, skilled and brilliant value family sport.',
    url: 'https://www.pulse.org.nz',
    img: '',
    pick: false,

    label: '🏐 ANZ Premiership Netball',
    labelStyle: 'color:#8A1A1A',
    family: 'Family',
    cost: 'Ticketed — pulse.org.nz',},
  {
    title: '& Juliet — St James Theatre',
    type: 'culture', day: 'fri', weekend: '2026-05-16', region: 'wellington',
    time: 'Friday 15 May · 7:30 pm',
    venue: 'St James Theatre, 77 Courtenay Place, Wellington',
    description: 'In its second week at the St James, the smash-hit West End and Broadway musical continues its New Zealand premiere run. & Juliet asks: what if Juliet didn\'t die? Packed with Max Martin anthems — Baby One More Time, Roar, Since U Been Gone, It\'s My Life and more. Friday night performances run throughout the three-week season.',
    url: 'https://www.stjamestheatre.co.nz',
    img: '',
    pick: false,

    label: '🎭 West End Musical',
    labelStyle: 'color:#8A1A5B',
    cost: 'Ticketed — stjamestheatre.co.nz',},
  {
    title: 'NZ International Comedy Festival — Final Fortnight',
    type: 'culture', day: 'sat', weekend: '2026-05-16', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'The Comedy Festival\'s final fortnight — shows are filling up and the best ones are often sold out by now, so book early. This weekend features David Correos, Elouise Eftos: APHRODITE, and Sashi Perera: Pear Tree among many others. Check the website for full listings.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: true,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},
  {
    title: 'Marlon Williams — Tā te Manawa Tour',
    type: 'music', day: 'sat', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'Marlon Williams and the Yarra Benders perform ahead of a planned sabbatical from the spotlight — this is billed as his last Kiwi tour for the foreseeable future. An extraordinary performer at his peak, playing his Wellington home crowd. Sold out but worth checking for resale tickets.',
    url: 'https://www.iticketpro.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: true,
  
    label: '🎤 Live Music · Farewell Tour',
    labelStyle: 'color:#8A1A1A',
    cost: 'Sold out — check resale',},
  {
    title: 'Zealandia — Twilight Wildlife Experience',
    type: 'outdoor', day: 'sat', weekend: '2026-05-16', region: 'wellington',
    time: 'Check schedule for tour times',
    venue: '53 Waiapu Rd, Karori',
    description: 'May is a brilliant time to visit Zealandia — the 500-acre predator-free sanctuary is home to kiwi, tuatara, kākā and rare waterfowl. Evening twilight tours give the best chance to spot kiwi in the wild. One of Wellington\'s most extraordinary experiences.',
    url: 'https://www.visitzealandia.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/KaroriWildlifeSanctuary.jpg/960px-KaroriWildlifeSanctuary.jpg',
    pick: false,
  
    label: '🌿 Winter Walk',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Adults $21 · Children $10.50 · Twilight tours extra',},

  // ── 22–25 May 2026 ───────────────────────────────────────────────────────
  {
    title: 'NZSO: Titan — Gemma New & James Ehnes',
    type: 'music', day: 'fri', weekend: '2026-05-23', region: 'wellington',
    time: 'Friday 22 May · 6:30 pm',
    venue: 'Michael Fowler Centre, 111 Wakefield Street, Wellington',
    description: 'Conductor Gemma New leads the NZSO with Grammy-winning violinist James Ehnes (Gramophone Artist of the Year 2021) in a stunning programme: a NZ premiere from Thomas Adès, the magnificent Korngold Violin Concerto, and Mahler\'s towering Symphony No. 1 "Titan". One of the great orchestral evenings of the Wellington year.',
    url: 'https://www.nzso.co.nz/events/titan',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: true,

    label: '🎻 NZSO · Grammy-winning Soloist',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — nzso.co.nz',},
  {
    title: 'Symphony in the Hutt — Free Community Concert',
    type: 'music', day: 'fri', weekend: '2026-05-23', region: 'lower-hutt',
    time: 'Friday 22 May · 7:00 pm',
    venue: 'Walter Nash Centre, Taita, Lower Hutt',
    description: 'Orchestra Wellington\'s annual free community concert — the orchestra performs alongside Arohanui Strings, the Sistema Hutt Valley youth programme, in a family-friendly gala programme of orchestral favourites. Free tickets available from Walter Nash Stadium reception. One of the most generous events in the Wellington music calendar.',
    url: 'https://orchestrawellington.co.nz/events/',
    img: '',
    pick: true,

    label: '🎻 Free Community Concert',
    labelStyle: 'color:#1A6B3A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Tommy Emmanuel & Mike Dawes',
    type: 'music', day: 'fri', weekend: '2026-05-23', region: 'wellington',
    time: 'Friday 22 May · Check schedule for time',
    venue: 'The Opera House, 111 Manners Street, Wellington',
    description: 'Two of the world\'s greatest acoustic guitarists on the same stage — Tommy Emmanuel CGP and Mike Dawes in an evening of jaw-dropping fingerstyle guitar. Tommy is one of Australia\'s most beloved musicians; Mike Dawes is a virtuoso in the same league. An intimate night of extraordinary musicianship at the beautiful Opera House.',
    url: 'https://www.theoperahouse.co.nz',
    img: '',
    pick: true,

    label: '🎸 Acoustic Guitar · World Class',
    labelStyle: 'color:#5B4A1A',
    cost: 'Ticketed — theoperahouse.co.nz',},
  {
    title: 'NZ International Comedy Festival — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'The very last weekend of the NZ International Comedy Festival — Saturday night shows are the final chance to catch any acts you haven\'t seen yet. Last-chance performances from the full line-up before the curtain falls for 2026.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: false,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},
  {
    title: 'Hurricanes v Highlanders',
    type: 'outdoor', day: 'sat', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Hurricanes host the Highlanders in what shapes up as a crucial Super Rugby fixture late in the season. Always a physical, passionate contest between two sides with proud rugby traditions. A great way to start a big Wellington weekend.',
    url: 'https://www.hurricanes.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Highlander_vs_Hurricanes_2005.jpg/960px-Highlander_vs_Hurricanes_2005.jpg',
    pick: false,
  
    label: '🌀 Super Rugby',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — hurricanes.flicket.co.nz',},
  {
    title: 'Eddie Izzard — The Remix: The First 35 Years',
    type: 'culture', day: 'sun', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'Eddie Izzard closes out the NZ International Comedy Festival with a one-person show remixing and reimagining highlights from 35 years of sell-out shows — from 1993\'s The Ambassadors to 2019\'s Wunderbar. One of the great stand-up performers of a generation, live in Wellington.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Eddie_Izzard_comes_to_Crouch_End.jpg/960px-Eddie_Izzard_comes_to_Crouch_End.jpg',
    pick: true,
  
    label: '😂 Comedy Festival · Closing Night',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed',},
  {
    title: 'Orpheus Choir Wellington — Glory (Carterton)',
    type: 'music', day: 'sun', weekend: '2026-05-23', region: 'wairarapa',
    time: 'Sunday 24 May · 2:00 pm – 4:00 pm',
    venue: 'Wairarapa Events Centre, 50 Holloway St, Carterton',
    description: 'Orpheus Choir Wellington performs Vivaldi\'s luminous Gloria alongside Mozart\'s deeply moving Requiem, with soloists from the NZ School of Music. Conductor Brent Stewart leads the choir in a programme of stunning sacred choral music — a beautiful afternoon in the Wairarapa.',
    url: 'https://www.orpheuschoir.org.nz/our-concerts/glory-carterton',
    img: '',
    pick: false,

    label: '🎶 Choral Concert · Wairarapa',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — orpheuschoir.org.nz',},
  {
    title: 'Wellington Saints vs Bay Hawks — NBL Basketball',
    type: 'outdoor', day: 'mon', weekend: '2026-05-23', region: 'wellington',
    time: 'Monday 25 May · 7:00 pm',
    venue: 'TSB Arena, 55 Cable Street, Wellington Waterfront',
    description: 'Wellington Saints host the Hawke\'s Bay Hawks in the Sal\'s NBL — New Zealand\'s premier domestic basketball competition. Fast, high-energy basketball in a compact arena where every seat is close to the action. A great way to end the long weekend.',
    url: 'https://nznbl.basketball/schedule/',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/2019_NCAA_Men%27s_Basketball_Finals_Game_3_crowd.jpg/960px-2019_NCAA_Men%27s_Basketball_Finals_Game_3_crowd.jpg',
    pick: false,

    label: '🏀 Sal\'s NBL Basketball',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — saints.co.nz',},

  // ── 29 May – 1 Jun 2026 (King's Birthday) ─────────────────────────────────
  {
    title: 'NZ Art Show 2026',
    type: 'culture', day: 'fri', weekend: '2026-05-30', region: 'wellington',
    time: 'Fri 29 May from 9:00 am · Sat–Sun 10:00 am (runs 29–31 May)',
    venue: 'TSB Arena & Shed 6, Wellington Waterfront',
    description: 'Aotearoa\'s premier art fair fills the waterfront across the King\'s Birthday long weekend — over 4,000 original works from 300+ artists spanning painting, sculpture, photography and emerging talent. Shed 6 spotlights up-and-coming artists. A brilliant day out for anyone who loves original art or wants to find something special for home.',
    url: 'https://www.artshow.co.nz',
    img: '',
    pick: true,

    label: '🖼 NZ Art Show · 4,000+ Works',
    labelStyle: 'color:#5B4A8A',
    family: 'Family',
    cost: 'Entry fee — artshow.co.nz',},
  {
    title: 'Marlon Williams — Tā te Manawa (2nd Wellington Show)',
    type: 'music', day: 'fri', weekend: '2026-05-30', region: 'wellington',
    time: 'Friday 29 May · 7:00 pm',
    venue: 'Michael Fowler Centre, 111 Wakefield Street, Wellington',
    description: 'A second Wellington date added after Saturday 23 May sold out — Marlon Williams and The Yarra Benders perform a double-set headline show ahead of his planned sabbatical from touring. Extraordinary live performer at his peak; this may be one of the last chances to see him for some time.',
    url: 'https://www.wellingtonnz.com/visit/events/marlon-williams',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: true,

    label: '🎤 Live Music · Second Date Added',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed',},
  {
    title: 'Heathers the Musical — Opening Weekend',
    type: 'culture', day: 'sat', weekend: '2026-05-30', region: 'wellington',
    time: 'Runs 28 May – 7 June · Various sessions',
    venue: 'The Opera House, 111 Manners Street, Wellington',
    description: 'The cult musical based on the 1988 dark comedy film opens at the Opera House. Darkly funny and sharply observed, with a killer rock score by Kevin Murphy and Laurence O\'Keefe. Directed by Andy Fickman. Runs through the King\'s Birthday long weekend. For older teens and adults.',
    url: 'https://heathersthemusical.com/new-zealand/tour-dates-nz/',
    img: '',
    pick: false,

    label: '🎭 Cult Musical · Opening',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed — theoperahouse.co.nz',},
  {
    title: 'Upper Hutt Music Festival — TNT! Jazz Gala',
    type: 'music', day: 'fri', weekend: '2026-05-30', region: 'upper-hutt',
    time: 'Friday 29 May · Check schedule for time',
    venue: 'Whirinaki Whare Taonga, 836 Fergusson Drive, Upper Hutt',
    description: 'The Upper Hutt Music Festival opens with a 19-piece jazz big band featuring vocalist Lisa Tomlins. Part of a multi-day festival running 29 May – 2 June at Whirinaki Whare Taonga. The Warratahs play Sunday 31 May.',
    url: 'https://uhconnection.co.nz/community-events/upper-hutt-music-festival-29th-of-may-2nd-of-june/',
    img: '',
    pick: false,

    label: '🎺 Jazz Big Band · Festival Opening',
    labelStyle: 'color:#C8901A',
    cost: '$25 — uhconnection.co.nz',},
  {
    title: 'The Warratahs — Upper Hutt Music Festival',
    type: 'music', day: 'sun', weekend: '2026-05-30', region: 'upper-hutt',
    time: 'Sunday 31 May · Check schedule for time',
    venue: 'Whirinaki Whare Taonga, 836 Fergusson Drive, Upper Hutt',
    description: 'The beloved NZ roots and country institution The Warratahs perform at the Upper Hutt Music Festival. One of Aotearoa\'s most enduring and warmly loved bands, with wide appeal across generations. A perfect Sunday evening show.',
    url: 'https://uhconnection.co.nz/community-events/upper-hutt-music-festival-29th-of-may-2nd-of-june/',
    img: '',
    pick: false,

    label: '🎶 NZ Roots · Beloved Institution',
    labelStyle: 'color:#C8901A',
    family: 'Family',
    cost: '$35–$40 — uhconnection.co.nz',},
  {
    title: 'Brewtown Record Convention — Aotearoa\'s Biggest Record Fair',
    type: 'culture', day: 'sun', weekend: '2026-05-30', region: 'upper-hutt',
    time: 'Sunday 31 May · From 10:00 am',
    venue: 'Brewtown, 27 Blenheim Street, Upper Hutt',
    description: 'The 4th annual Brewtown Record Convention — hundreds of thousands of new and pre-loved vinyl LPs, EPs, singles and music formats from multiple vendors. Books, posters, T-shirts and art too. Free entry and browsable in the craft brewery precinct. Combine with a beer and a burger for a perfect winter Sunday.',
    url: 'https://www.brewtown.co.nz',
    img: '',
    pick: false,

    label: '💿 Vinyl Record Fair · Free Entry',
    labelStyle: 'color:#1A1A6A',
    free: 'Free entry',
    family: 'Family',},
  {
    title: 'Orchestra Wellington — W:ELLINGTON',
    type: 'music', day: 'sat', weekend: '2026-05-30', region: 'wellington',
    time: 'Saturday 30 May · 7:30 pm (pre-concert talk 6:30 pm)',
    venue: 'Michael Fowler Centre, 111 Wakefield Street, Wellington',
    description: 'Orchestra Wellington\'s "Collaborations" season concert — check their website for the full programme. Pre-concert talk in the Renouf Foyer from 6:30 pm for those wanting deeper context. A great Wellington winter evening out.',
    url: 'https://orchestrawellington.co.nz/events/',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: false,

    label: '🎻 Orchestra Wellington',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — orchestrawellington.co.nz',},

  // ── 5–8 Jun 2026 ─────────────────────────────────────────────────────────
  {
    title: 'NZSO: Romeo & Juliet — Barber & Prokofiev',
    type: 'music', day: 'fri', weekend: '2026-06-06', region: 'wellington',
    time: 'Friday 5 June · 6:30 pm',
    venue: 'Michael Fowler Centre, 111 Wakefield Street, Wellington',
    description: 'Conductor Benjamin Northey leads the NZSO with cellist Li-Wei Qin in a programme of exquisite sweep: Samuel Barber\'s aching Cello Concerto, Prokofiev\'s selections from Romeo and Juliet, and a new work from Kenneth Young. Li-Wei Qin is one of the world\'s finest cellists — a very special Wellington evening.',
    url: 'https://www.nzso.co.nz/events/romeo-and-juliet',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: true,

    label: '🎻 NZSO · Cello & Romeo & Juliet',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — nzso.co.nz',},
  {
    title: 'Sola Rosa — In the Mids Tour',
    type: 'music', day: 'sat', weekend: '2026-06-06', region: 'wellington',
    time: 'Saturday 6 June · 7:00 pm',
    venue: 'San Fran, 171 Cuba Street, Wellington',
    description: 'Acclaimed NZ producer Andrew Spraggon (Sola Rosa) tours his tenth studio album In the Mids — seven collaborations with vocalists from across Aotearoa and Australia, performed live with a newly developed visual and lighting design. A Wellington institution returns to one of Wellington\'s best small venues.',
    url: 'https://www.undertheradar.co.nz',
    img: '',
    pick: false,

    label: '🎵 NZ Music · Sola Rosa',
    labelStyle: 'color:#1A6B3A',
    cost: 'Ticketed — undertheradar.co.nz',},
  {
    title: 'Orpheus Choir Wellington — Glory (Kāpiti)',
    type: 'music', day: 'sat', weekend: '2026-06-06', region: 'kapiti',
    time: 'Saturday 6 June · 7:00 pm',
    venue: 'Te Raukura ki Kāpiti, 32 Raumati Road, Raumati Beach',
    description: 'Orpheus Choir Wellington brings their Glory programme to the Kāpiti Coast — Vivaldi\'s radiant Gloria and Mozart\'s deeply moving Requiem, with soloists from the NZ School of Music. The Raumati Beach venue is a beautiful setting for an outstanding choral evening.',
    url: 'https://www.orpheuschoir.org.nz/our-concerts',
    img: '',
    pick: false,

    label: '🎶 Choral Concert · Kāpiti',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — orpheuschoir.org.nz',},

  // ── 12–15 Jun 2026 (Matariki season) ─────────────────────────────────────
  {
    title: 'Mana Moana Pōneke — Matariki Water Screen',
    type: 'culture', day: 'sat', weekend: '2026-06-13', region: 'wellington',
    time: 'Weekend evenings 12–15 June · Part of a 7–22 June season',
    venue: 'Whairepo Lagoon, Wellington Waterfront',
    description: 'Indigenous short films by Māori and Pasifika artists are projected onto a stunning water screen made from millions of water droplets at the waterfront lagoon. Part of Wellington\'s Matariki festival season. Completely free and unlike anything else — an unforgettable visual experience in the crisp winter air.',
    url: 'https://wellington.govt.nz/news-and-events/events-and-festivals/matariki',
    img: '',
    pick: true,

    label: '🌊 Matariki Water Screen · Free',
    labelStyle: 'color:#0B5563',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Matariki Market at Wharewaka',
    type: 'market', day: 'sun', weekend: '2026-06-13', region: 'wellington',
    time: 'Sunday 14 June · 10:00 am – 3:00 pm',
    venue: 'Te Wharewaka o Pōneke, 2 Taranaki Street, Wellington Waterfront',
    description: 'A beautiful Māori and Tangata Moana creative market at the waterfront — original art, pounamu, handmade taonga, vintage clothing and more. Karaka Cafe next door for coffee and kai. A wonderful way to celebrate Matariki season and support Māori and Pasifika creators.',
    url: 'https://wellington.govt.nz/news-and-events/events-and-festivals/matariki',
    img: '',
    pick: false,

    label: '🛒 Matariki Market · Free Entry',
    labelStyle: 'color:#1A6B3A',
    free: 'Free entry',
    family: 'Family',},

  // ── 19–22 Jun 2026 (Matariki Ahi Kā) ────────────────────────────────────
  {
    title: 'Matariki Ahi Kā — Wellington Waterfront Festival',
    type: 'festival', day: 'fri', weekend: '2026-06-20', region: 'wellington',
    time: 'Friday 19 – Monday 22 June · 6:00 pm – 9:00 pm each evening',
    venue: 'Wellington Waterfront, Barnett Street area',
    description: 'Wellington\'s most spectacular free annual event — a journey through Past, Present and Future across the waterfront. Fire installations, large-scale projections onto buildings and water, live performances, interactive storytelling, traditional Māori games, kai from food trucks, and a ceremonial procession each evening at 7:40 pm. Running all four evenings of the long Matariki weekend. Completely free.',
    url: 'https://www.wellingtonnz.com/visit/events/matariki-ahi-ka',
    img: '',
    pick: true,

    label: '🌟 Matariki Ahi Kā · Free · 4 Nights',
    labelStyle: 'color:#0A4A6A',
    stripStyle: 'background:linear-gradient(90deg,#0A1A2A,#1a4a6a)',
    free: 'Free',
    family: 'Family',},
  {
    title: 'NZ Opera — The Marriage of Figaro',
    type: 'culture', day: 'fri', weekend: '2026-06-20', region: 'wellington',
    time: 'Fri 19 June 7:30 pm · Sun 21 June 2:30 pm',
    venue: 'St James Theatre, 77 Courtenay Place, Wellington',
    description: 'Mozart\'s beloved comic masterpiece performed by NZ Opera with Orchestra Wellington — the Wellington premiere of a production originally planned for 2021 and delayed by COVID. Directed by Lindy Hume, conducted by James Judd, with a stellar NZ cast. Two performances at the beautifully restored St James.',
    url: 'https://nzopera.com/opera/the-marriage-of-figaro/',
    img: '',
    pick: true,

    label: '🎭 NZ Opera · Mozart',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — nzopera.com',},
  {
    title: 'Winter Solstice at Stonehenge Aotearoa',
    type: 'outdoor', day: 'sun', weekend: '2026-06-20', region: 'wairarapa',
    time: 'Sunday 21 June · From 4:00 pm (sunset ~4:30 pm)',
    venue: 'Stonehenge Aotearoa, 51 Ahiaruhe Road, Carterton, Wairarapa',
    description: 'Watch the sun set over the winter heel stone at Aotearoa\'s own astronomical henge on the longest night of the year. Introduction from 4:00 pm covering the history and purpose of the site — a moving and memorable way to mark the winter solstice. Small group event, book ahead.',
    url: 'https://stonehenge-aotearoa.nz/events/winter-solstice/',
    img: '',
    pick: false,

    label: '🌑 Winter Solstice · Wairarapa',
    labelStyle: 'color:#1A1A4A',
    cost: 'Ticketed — stonehenge-aotearoa.nz',
    family: 'Family',},

  // ── 26–29 Jun 2026 ───────────────────────────────────────────────────────
  {
    title: 'Engelbert Humperdinck — The Celebration Tour',
    type: 'music', day: 'fri', weekend: '2026-06-27', region: 'wellington',
    time: 'Friday 26 June · 7:00 pm',
    venue: 'Michael Fowler Centre, 111 Wakefield Street, Wellington',
    description: 'At 89, British pop legend Engelbert Humperdinck returns to New Zealand for the first time since 2019 — performing his timeless classics (Release Me, The Last Waltz, A Man Without Love) with his full band. An extraordinary evening for fans of a true entertainer who has sold over 150 million records worldwide.',
    url: 'https://www.livenation.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: false,

    label: '🎤 Pop Legend · 89 Years Young',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed — livenation.co.nz',},
  {
    title: 'Te Wehi — I\'m Home NZ Album Tour',
    type: 'music', day: 'fri', weekend: '2026-06-27', region: 'wellington',
    time: 'Friday 26 June · Check schedule for time',
    venue: 'St James Theatre, 77 Courtenay Place, Wellington',
    description: 'Acclaimed NZ Māori singer Te Wehi celebrates the release of her debut album I\'m Home with a national tour. A powerful voice and deeply personal music rooted in Māori language and culture — a beautiful Wellington evening for music lovers.',
    url: 'https://www.stjamestheatre.co.nz',
    img: '',
    pick: false,

    label: '🎤 NZ Māori Music · Debut Album',
    labelStyle: 'color:#1A6B3A',
    cost: 'Ticketed',},
  {
    title: 'Orchestra Wellington — Virtuosi',
    type: 'music', day: 'sat', weekend: '2026-06-27', region: 'wellington',
    time: 'Saturday 27 June · 7:30 pm (pre-concert talk 6:30 pm)',
    venue: 'Michael Fowler Centre, 111 Wakefield Street, Wellington',
    description: 'Orchestra Wellington\'s Collaborations season finale — check their website for the programme, which will be announced closer to the date. Pre-concert talk from 6:30 pm for context and insight. A great closing event to a rich Wellington winter music season.',
    url: 'https://orchestrawellington.co.nz/events/',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: false,

    label: '🎻 Orchestra Wellington · Season Finale',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed — orchestrawellington.co.nz',},
  {
    title: 'Wellington Marathon 2026',
    type: 'outdoor', day: 'sun', weekend: '2026-06-27', region: 'wellington',
    time: 'Sunday 28 June · From 7:00 am',
    venue: 'Start: Hnry Stadium Walkway, Wellington Waterfront',
    description: 'The 39th Wellington Marathon — a flat, scenic harbour course past Te Papa, along Oriental Parade and out to Scorching Bay. Options from the Kids\' Magic Mile to Full Marathon. Around 4,000 runners from 20+ countries. A brilliant spectator event along the waterfront even if you\'re not running — cheer the field home.',
    url: 'https://www.wellingtonmarathon.co.nz',
    img: '',
    pick: false,

    label: '🏃 Wellington Marathon',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Ticketed for runners · Free to spectate',},

  // ── 25–28 Apr (ANZAC weekend) additional ─────────────────────────────────
  {
    title: 'Wellington Saints v Auckland Tuatara — NBL Basketball',
    type: 'outdoor', day: 'mon', weekend: '2026-04-25', region: 'wellington',
    time: 'Monday 27 April · 5:00 pm',
    venue: 'TSB Arena, 50 Cable St, Wellington',
    description: 'Wellington Saints host the Auckland Tuatara in this ANZAC Week NBL home game at TSB Arena. Fast-paced professional basketball in a great atmosphere — the Saints are Wellington\'s team in NZ\'s premier basketball league.',
    url: 'https://www.wellingtonsaints.co.nz',
    img: '',
    pick: false,

    label: '🏀 NBL Basketball',
    labelStyle: 'color:#D44820',
    family: 'Family',
    cost: 'Ticketed — wellingtonsaints.co.nz',},

  // ── 1–4 May additional ────────────────────────────────────────────────────
  {
    title: 'Fat Freddy\'s Drop — Based On A True Story (Opening Night)',
    type: 'music', day: 'fri', weekend: '2026-05-02', region: 'wellington',
    time: 'Friday 1 May · Doors 7:00 pm · Show 7:30 pm',
    venue: 'Michael Fowler Centre, 111 Wakefield St, Wellington',
    description: 'Three-night Wellington homecoming — Fat Freddy\'s Drop perform their landmark debut album \'Based On A True Story\' in full for the first time ever, to mark its 21st anniversary. Opening night of three. All ages.',
    url: 'https://fatfreddysdrop.com',
    img: '',
    pick: true,

    label: '🎶 Fat Freddy\'s Drop',
    labelStyle: 'color:#7A3B8A',
    family: 'All Ages',
    cost: 'Ticketed',},

  // ── 8–11 May additional ───────────────────────────────────────────────────
  {
    title: 'Hurricanes v Moana Pasifika — Super Rugby Pacific',
    type: 'outdoor', day: 'sat', weekend: '2026-05-09', region: 'wellington',
    time: 'Saturday 9 May · 5:05 pm',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Hurricanes host Moana Pasifika at Hnry Stadium in Super Rugby Pacific Round 13. A fiercely physical matchup featuring some of the Pacific\'s best rugby talent — great atmosphere under lights.',
    url: 'https://hurricanes.flicket.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Hurricanes_vs_Waratahs_2015.jpg/960px-Hurricanes_vs_Waratahs_2015.jpg',
    pick: false,

    label: '🌀 Super Rugby',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — hurricanes.flicket.co.nz',},

  // ── 22–25 May additional ──────────────────────────────────────────────────
  {
    title: 'Not In Our Neighbourhood — Circa Theatre',
    type: 'culture', day: 'sat', weekend: '2026-05-23', region: 'wellington',
    time: 'Sat 23 May – Sat 13 Jun · Tue–Sat 7:00 pm · Sun 4:00 pm',
    venue: 'Circa Theatre, 1 Taranaki St, Te Aro, Wellington',
    description: 'A new New Zealand play told through a filmmaker\'s lens, following a group of women whose lives intersect at a moment of neighbourhood conflict. Part of Circa\'s 2026 season — sharp, contemporary storytelling.',
    url: 'https://www.circa.co.nz',
    img: '',
    pick: false,

    label: '🎭 New NZ Play',
    labelStyle: 'color:#8A3B1A',
    family: 'Teens+',
    cost: 'Ticketed — circa.co.nz',},

  // ── 29 May – 1 Jun additional ─────────────────────────────────────────────
  {
    title: 'Julia — Circa Theatre (Preview & Opening)',
    type: 'culture', day: 'fri', weekend: '2026-05-30', region: 'wellington',
    time: 'Fri 29 May (preview) · Sat 30 May (opens) · 7:00 pm',
    venue: 'Circa One, 1 Taranaki St, Te Aro, Wellington',
    description: 'Lara Macgregor plays Julia Gillard in the moment of her landmark 2012 misogyny speech. Written by Joanna Murray-Smith — gripping, urgent, and darkly funny. 100 minutes. Runs 29 May to 27 Jun. Ages 13+.',
    url: 'https://www.circa.co.nz/package/julia/',
    img: '',
    pick: true,

    label: '🎭 Circa Theatre',
    labelStyle: 'color:#8A3B1A',
    family: 'Teens+',
    cost: 'From $25 — circa.co.nz',},
  {
    title: 'Sean Kelly & The Super 8\'s — Upper Hutt Music Festival',
    type: 'music', day: 'sat', weekend: '2026-05-30', region: 'upper-hutt',
    time: 'Saturday 30 May · 7:30 pm',
    venue: 'Whirinaki Whare Taonga, 836 Fergusson Dr, Upper Hutt',
    description: 'Irish singer Sean Kelly with Jono Lonie (fiddle/mandolin) and Maree Limpus (cello) bring an evening of Celtic and folk warmth to Upper Hutt as part of the Music Festival. Intimate and uplifting.',
    url: 'https://www.whirinakiarts.org.nz',
    img: '',
    pick: false,

    label: '🎻 Celtic Folk',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: '$25',},

  // ── 5–8 Jun additional ────────────────────────────────────────────────────
  {
    title: 'Come Together — Born to Run (Springsteen Night)',
    type: 'music', day: 'fri', weekend: '2026-06-06', region: 'wellington',
    time: 'Friday 5 June · 8:00 pm',
    venue: 'St James Theatre, 77 Courtenay Place, Wellington',
    description: 'NZ\'s acclaimed \'Come Together\' tribute series performs Springsteen\'s Born to Run album in full, plus a second set of classics. Featuring Milan Borich, Adam McGrath, Jennie Skulander, Jon Toogood (Shihad) and the full band.',
    url: 'https://www.stjames.co.nz',
    img: '',
    pick: true,

    label: '🎸 Springsteen Night',
    labelStyle: 'color:#7A3B8A',
    family: 'Teens+',
    cost: 'Ticketed — stjames.co.nz',},
  {
    title: 'Wellington Baby Expo 2026',
    type: 'kids', day: 'sat', weekend: '2026-06-06', region: 'lower-hutt',
    time: 'Sat–Sun 6–7 June · 9:00 am – 4:00 pm',
    venue: 'Lower Hutt Events Centre, 30 Laings Rd, Lower Hutt',
    description: 'Annual baby and parenting expo with products, services, and expert advice for expectant parents and families. Prams, nursery, sleep, feeding, clothing, healthcare — everything in one place.',
    url: 'https://www.aradapromotions.co.nz',
    img: '',
    pick: false,

    label: '👶 Baby & Parenting Expo',
    labelStyle: 'color:#D44895',
    family: 'Family',
    cost: 'Ticketed',},
  {
    title: 'Wellington Saints v Otago Nuggets — NBL Basketball',
    type: 'outdoor', day: 'sun', weekend: '2026-06-06', region: 'wellington',
    time: 'Sunday 7 June · 3:00 pm',
    venue: 'TSB Arena, 50 Cable St, Wellington',
    description: 'Wellington Saints host the Otago Nuggets in a Sal\'s NBL home fixture. Fast-paced professional basketball with a passionate home crowd at TSB Arena.',
    url: 'https://www.wellingtonsaints.co.nz',
    img: '',
    pick: false,

    label: '🏀 NBL Basketball',
    labelStyle: 'color:#D44820',
    family: 'Family',
    cost: 'Ticketed — wellingtonsaints.co.nz',},

  // ── 12–15 Jun additional ──────────────────────────────────────────────────
  {
    title: 'Te Hau o Matariki — Ngāti Toa Rangatira at Te Papa',
    type: 'culture', day: 'sat', weekend: '2026-06-13', region: 'wellington',
    time: 'Saturday 13 June · 11:00 am – 4:00 pm',
    venue: 'Te Papa Tongarewa, 55 Cable St, Wellington',
    description: 'A free day of music, storytelling, and art from Ngāti Toa Rangatira as part of Matariki at Te Papa. Drop in to connect with the stories of the people of the Kāpiti and Cook Strait region.',
    url: 'https://www.tepapa.govt.nz/visit/events',
    img: '',
    pick: false,

    label: '🌟 Matariki — Free',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Free',},
  {
    title: 'Kids\' Concert — Konohete a ngā tamariki (Te Papa)',
    type: 'kids', day: 'sun', weekend: '2026-06-13', region: 'wellington',
    time: 'Sunday 14 June · 2:00 pm – 4:00 pm',
    venue: 'Te Papa Tongarewa, 55 Cable St, Wellington',
    description: 'A joyful children\'s concert performed by tamariki from six Wellington early childhood centres, celebrating Matariki at Te Papa. Singing, waiata and performances — free, all welcome.',
    url: 'https://www.tepapa.govt.nz/visit/events',
    img: '',
    pick: true,

    label: '🌟 Matariki Kids — Free',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Free',},

  // ── 26–29 Jun additional ──────────────────────────────────────────────────
  {
    title: 'Wellington Saints v Nelson Giants — NBL Basketball',
    type: 'outdoor', day: 'fri', weekend: '2026-06-27', region: 'wellington',
    time: 'Friday 26 June · 7:30 pm',
    venue: 'TSB Arena, 50 Cable St, Wellington',
    description: 'Wellington Saints host the Nelson Giants in a Friday night Sal\'s NBL home game. Great live sport for the family — fast-paced basketball at TSB Arena.',
    url: 'https://www.wellingtonsaints.co.nz',
    img: '',
    pick: false,

    label: '🏀 NBL Basketball',
    labelStyle: 'color:#D44820',
    family: 'Family',
    cost: 'Ticketed — wellingtonsaints.co.nz',},
  {
    title: 'Kaumatua Kapa Haka — Te Papa Matariki',
    type: 'culture', day: 'sat', weekend: '2026-06-27', region: 'wellington',
    time: 'Sat–Sun 27–28 June · 10:00 am – 4:00 pm',
    venue: 'Te Papa Tongarewa, 55 Cable St, Wellington',
    description: 'Two days of kapa haka and waiata performed by kaumātua (elders) as part of Matariki at Te Papa. A deeply moving celebration of Māori song and movement by experienced performers. Free with museum entry.',
    url: 'https://www.tepapa.govt.nz/visit/events',
    img: '',
    pick: false,

    label: '🌟 Matariki — Free',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Free',},
];
