// ── Static event data ─────────────────────────────────────────────────────────
// Single source of truth for all curated/static events.
// Both the main site (js/script.js) and admin portal (admin/admin.js) read from
// this array so every event is rendered by the same function and is visible in
// the admin portal.
//
// Fields mirror the Firestore event schema used by handleFormSubmit():
//   title, description, type, day, weekend, region, venue, time, url, img, pick
//
// The admin "Import drafts" button imports any unimported events here into
// Firestore so they can be edited and managed via the admin interface.
// ─────────────────────────────────────────────────────────────────────────────
const STATIC_EVENTS = [
  // ── 28 Feb – 1 Mar 2026 ──────────────────────────────────────────────────
  {
    title: 'Wellington Art Show 2026',
    type: 'culture', day: 'sat', weekend: '2026-02-28', region: 'wellington',
    time: 'Sat 10:00 am – 8:00 pm (runs 27 Feb–1 Mar)',
    venue: 'Tākina Convention Centre, 50 Cable St',
    description: 'Thousands of original works across painting, ceramics, jewellery, textiles and sculpture, plus live artist demonstrations. Kids under 16 free with a paying adult.',
    url: 'https://www.wellingtonartshow.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Trapezegallery.jpg',
    pick: true,
  
    label: '🎨 Art Show',
    labelStyle: 'color:#5B4A8A',
    ticketed: true,
    family: 'Family',
    cost: 'Weekend pass $10 · Under 16s free with adult',},
  {
    title: '20 Summers Fest — Home Alone Records',
    type: 'music', day: 'sat', weekend: '2026-02-28', region: 'wellington',
    time: 'Doors 1:00 pm · Gig from 1:15 pm',
    venue: 'Central Wellington (venue TBA)',
    description: 'Home Alone Records celebrates 20 years with 10+ acts including French for Rabbits, Lake South and Young Moon. All ages, tamariki under 12 free — a genuinely special afternoon of NZ music.',
    url: 'https://www.eventfinda.co.nz/whatson/events/wellington',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Chris_Ellis_music_340_%2851501975643%29.jpg/960px-Chris_Ellis_music_340_%2851501975643%29.jpg',
    pick: true,
  
    label: '🎶 Live Music',
    labelStyle: 'color:#7A3B8A',
    family: 'All Ages',
    cost: 'Children under 12 free',},
  {
    title: 'NZ Festival of the Arts 2026',
    type: 'culture', day: 'sat', weekend: '2026-02-28', region: 'wellington',
    time: '24 Feb – 15 Mar · Multiple sessions daily',
    venue: 'Wellington CBD — multiple venues',
    description: 'The 40th anniversary edition of NZ\'s premier arts festival — dance, music, theatre and free whānau zones with face-painting and storytelling. Free street performances at Civic Square all weekend.',
    url: 'https://www.festival.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Arts_Festival_Premiere_Weekend_%2826707354691%29.jpg/960px-Arts_Festival_Premiere_Weekend_%2826707354691%29.jpg',
    pick: true,
  
    label: '🎨 Arts Festival',
    labelStyle: 'color:#5B4A8A',
    family: 'All Ages',
    cost: 'Mix of free & ticketed',},
  {
    title: 'Wellington Art Show — Final Day',
    type: 'culture', day: 'sun', weekend: '2026-02-28', region: 'wellington',
    time: 'Sunday 10:00 am – 5:00 pm',
    venue: 'Tākina Convention Centre, 50 Cable St',
    description: 'Last chance to explore hundreds of original NZ artworks before the show closes. Live artist demonstrations and a beautiful gallery atmosphere at Tākina.',
    url: 'https://www.wellingtonartshow.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Trapezegallery.jpg',
    pick: false,
  
    label: '🎨 Art Show',
    labelStyle: 'color:#5B4A8A',
    ticketed: true,
    family: 'Family',
    cost: 'Weekend pass $10 · Under 16s free with adult',},
  {
    title: 'NZ Fringe Festival 2026',
    type: 'culture', day: 'sun', weekend: '2026-02-28', region: 'wellington',
    time: 'Running until 7 March · Various times',
    venue: 'Multiple venues across Wellington',
    description: '178 shows across theatre, comedy, dance, circus and interactive performance. whānau-friendly showcases throughout — check the programme for family picks this weekend.',
    url: 'https://www.fringe.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/WPG_Fringe_2018.jpg/960px-WPG_Fringe_2018.jpg',
    pick: false,
  
    label: '🎭 Fringe Festival',
    labelStyle: 'color:#5B4A8A',
    free: 'Some free',
    family: 'Family',},

  // ── 7–8 Mar 2026 ─────────────────────────────────────────────────────────
  {
    title: 'Martinborough Fair 2026',
    type: 'festival', day: 'sat', weekend: '2026-03-07', region: 'wairarapa',
    time: 'Saturday 8:00 am – 4:00 pm',
    venue: 'Martinborough Square, Martinborough',
    description: 'Nearly 500 stalls of handmade goods, jewellery, pottery, woodwork, clothing, plants and street food. Live music, big bubbles, face painting and all proceeds to local charities. A proper day out — worth the drive over the hill.',
    url: 'https://www.eventfinda.co.nz/2026/martinborough-fair/martinborough',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/NZ-Martinborough.jpg/960px-NZ-Martinborough.jpg',
    pick: true,
  
    label: '🎪 Street Fair',
    labelStyle: 'color:#C8901A',
    free: 'Free entry',
    family: 'Family',},
  {
    title: 'Wellington Pride Parade 2026',
    type: 'festival', day: 'sat', weekend: '2026-03-07', region: 'wellington',
    time: 'Saturday 5:30 pm – 7:00 pm',
    venue: 'Courtenay Place & Dixon Street, Te Aro',
    description: 'Wellington\'s iconic Pride Parade — music, performers, DJs and a joyful community atmosphere. An inclusive celebration welcoming all whānau to watch or march. Part of Wellington Pride Festival 6–22 March.',
    url: 'https://www.wellingtonpridefestival.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GayPrideParade.jpg/960px-GayPrideParade.jpg',
    pick: true,
  
    label: '🌈 Pride Parade',
    labelStyle: 'color:#8b4bcc',
    stripStyle: 'background:linear-gradient(90deg,#e74c8b,#f0a030,#3ab065,#2980b9,#8b4bcc)',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Wellington Tramway Museum — Ride the Trams',
    type: 'outdoor', day: 'sun', weekend: '2026-03-07', region: 'kapiti',
    time: 'Sundays 11:00 am – 4:30 pm',
    venue: 'Queen Elizabeth Park, Paekakariki',
    description: 'Ride historic Wellington trams through beautiful Queen Elizabeth Park to the beach. Kids adore this — a true Wellington treasure delighting families for decades.',
    url: 'https://www.wellingtontrams.org.nz',
    img: '',
    pick: false,
  
    label: '🚂 Heritage Trams',
    labelStyle: 'color:#1A8A6E',
    family: 'Family',
    cost: 'Small fee',},
  {
    title: 'Newtown Festival',
    type: 'festival', day: 'sun', weekend: '2026-03-07', region: 'wellington',
    time: 'Sunday 8 March · 12pm – 6pm',
    venue: 'Riddiford St, Newtown, Wellington',
    description: 'Wellington\'s most beloved free community festival — live music on multiple stages, street food, stalls and arts celebrating Newtown\'s vibrant community. A genuine Wellington institution, perfect for all ages.',
    url: 'https://www.newtownfestival.org.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Newtown_Festival_2017.jpg/960px-Newtown_Festival_2017.jpg',
    pick: true,
  
    label: '🎪 Community Festival',
    labelStyle: 'color:#E8610A',
    free: 'Free',
    family: 'Family',},

  // ── 14–15 Mar 2026 ───────────────────────────────────────────────────────
  {
    title: 'Wellington Waterfront Parkrun',
    type: 'outdoor', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: 'Saturday 8:00 am (briefing 7:45 am)',
    venue: 'Frank Kitts Park, Wellington Waterfront',
    description: 'Free weekly 5km run/walk along Wellington\'s beautiful waterfront. All paces welcome — register once at parkrun.co.nz and run anywhere in the world forever.',
    url: 'https://www.parkrun.co.nz/wellington/',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Bushy_parkrun_27th_September_2014_%2815194006519%29.jpg/960px-Bushy_parkrun_27th_September_2014_%2815194006519%29.jpg',
    pick: false,
  
    label: '🏃 Parkrun',
    labelStyle: 'color:#1A8A6E',
    free: 'Free',
    family: 'All Ages',},
  {
    title: 'Wētā Workshop Unleashed',
    type: 'culture', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: 'Daily 9:00 am – 5:30 pm · Last tour 4:00 pm',
    venue: '1 Wētā Way, Miramar',
    description: 'Walk-through experiences, prop workshops and jaw-dropping creature effects at the world-famous Wētā Workshop. Book ahead — older kids and teens love this.',
    url: 'https://www.wetaworkshop.com/tours/wellington',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Weta_Workshop_Gandalf.jpg/960px-Weta_Workshop_Gandalf.jpg',
    pick: false,
  
    label: '🦖 Experience',
    labelStyle: 'color:#5B4A8A',
    ticketed: true,
    family: 'Family',},
  {
    title: 'Wellington Phoenix Double Header',
    type: 'outdoor', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: 'Saturday 14 March · Check Ticketek for times',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'A rare A-League double header — two Phoenix games at Hnry Stadium on the same day. The Phoenix are pushing for finals football and home games have electric atmosphere. Great live sport for families — bring a scarf and your voice.',
    url: 'https://www.wellingtonphoenix.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Crowd_at_WPX_vs_MBV_game_on_26_August_2007.jpg',
    pick: true,
  
    label: '⚽ A-League · Double Header',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — premier.ticketek.co.nz',},
  {
    title: 'NZ Festival of the Arts — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: '14–15 March · Last chance weekend',
    venue: 'Wellington CBD — multiple venues',
    description: 'Final weekend of NZ\'s premier arts festival — don\'t miss your last chance to catch world-class performances, free Civic Square street acts and the whānau zones. Unmissable Wellington event.',
    url: 'https://www.festival.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Spiky_performance_%2814775440009%29.jpg/960px-Spiky_performance_%2814775440009%29.jpg',
    pick: true,
  
    label: '🎨 Arts Festival',
    labelStyle: 'color:#5B4A8A',
    family: 'All Ages',
    cost: 'Mix of free & ticketed',},
  {
    title: 'Wellington Lantern Festival — Year of the Horse',
    type: 'festival', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: 'Thu 12 – Sun 15 Mar · Nightly from 4 pm, until 10 pm Fri–Sun',
    venue: 'Wellington Botanic Garden Ki Paekākā',
    description: 'A magical journey of lights through the Botanic Garden — from the main gate up Pinehill Path, through the Herb Garden, and down through the Lady Norwood Rose Garden and the Dell. Hundreds of lanterns, live performances on the Dell Stage, and festive atmosphere for the whole whānau.',
    url: 'https://www.facebook.com/events/701959832589342/',
    img: 'https://upload.wikimedia.org/wikipedia/commons/3/36/China-Shanghai-YuGarden-the_Lantern_Festival-2012_1828.JPG',
    pick: true,
    label: '🏮 Lantern Festival',
    labelStyle: 'color:#C8901A',
    free: 'Free entry',
    family: 'All Ages',},
  {
    title: 'Out in the City — Pride Family Fair',
    type: 'festival', day: 'sun', weekend: '2026-03-14', region: 'wellington',
    time: 'Sunday — all day (check wellingtonpridefestival.com)',
    venue: 'Odlins Plaza, Wellington Waterfront',
    description: 'Wellington Pride Festival\'s free all-ages family fair — live performances, food stalls, activities for tamariki and a joyful inclusive atmosphere on the waterfront. Part of Wellington Pride Festival 6–22 March.',
    url: 'https://www.wellingtonpridefestival.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GayPrideParade.jpg/960px-GayPrideParade.jpg',
    pick: true,
  
    label: '🌈 Pride Festival',
    labelStyle: 'color:#8b4bcc',
    stripStyle: 'background:linear-gradient(90deg,#e74c8b,#f0a030,#3ab065,#2980b9,#8b4bcc)',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Te Matapihi ki te Ao Nui — Wellington Library Opening Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-14', region: 'wellington',
    time: '14–15 March · Opening celebration',
    venue: 'Te Matapihi ki te Ao Nui / Te Ngākau Civic Square, Wellington CBD',
    description: 'The grand reopening of Wellington Central Library and Te Ngākau Civic Square — explore new community spaces, exhibitions and events across the weekend. A celebration for the whole whānau. Free entry.',
    url: 'https://wellington.govt.nz/news-and-events/events-and-festivals',
    img: '',
    pick: true,

    label: '📚 Free · Grand Opening',
    labelStyle: 'color:#1A5E8A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Ōtaki International Kite Festival',
    type: 'festival', day: 'sat', weekend: '2026-03-14', region: 'kapiti',
    time: '10:00 am – 4:00 pm',
    venue: 'Ōtaki Beach, Kāpiti Coast',
    description: 'Free annual kite festival with NZ Kite Association fliers — watch spectacular kites fill the sky above the beach. Hands-on fun for all ages.',
    url: 'https://kapiticoast.govt.nz/explore-kapiti/things-to-do-in-kapiti/whats-on/events-in-kapiti/',
    img: '',
    pick: false,

    label: '🪁 Free Festival',
    labelStyle: 'color:#2478A8',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Kapiti Classic 2026',
    type: 'music', day: 'sat', weekend: '2026-03-14', region: 'kapiti',
    time: '11:00 am – 7:00 pm',
    venue: 'Kāpiti Coast (venue TBC)',
    description: 'Summer music festival celebrating nostalgic New Zealand acts — a day of classic Kiwi music and good vibes on the Kāpiti Coast.',
    url: 'https://kapiticoast.govt.nz/explore-kapiti/things-to-do-in-kapiti/whats-on/events-in-kapiti/',
    img: '',
    pick: false,

    label: '🎶 Music Festival',
    labelStyle: 'color:#7A3B8A',
    cost: 'Ticketed',},

  // ── 21–22 Mar 2026 ───────────────────────────────────────────────────────
  {
    title: 'Hutt City Autumn Festival',
    type: 'outdoor', day: 'sat', weekend: '2026-03-21', region: 'lower-hutt',
    time: 'Saturday 10:00 am – 4:00 pm',
    venue: 'Riddiford Gardens, Lower Hutt',
    description: 'Riddiford Gardens bursts into colour in autumn — a beautiful park full of mature trees turning gold and red. Bring a picnic, let the kids loose on the grass and enjoy the seasonal colours at their peak.',
    url: 'https://www.lowerhutt.govt.nz/parks-recreation',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Lower_Hutt_2024_aerial_shot.jpg/960px-Lower_Hutt_2024_aerial_shot.jpg',
    pick: false,
  
    label: '🌸 Festival',
    labelStyle: 'color:#1A8A6E',
    free: 'Free',
    family: 'Family',},
  {
    title: 'St Patrick\'s Day Parade & Festival on the Waterfront',
    type: 'festival', day: 'sun', weekend: '2026-03-21', region: 'wellington',
    time: 'Sunday 1:00 pm – 4:30 pm',
    venue: 'Queens Wharf, Wellington Waterfront',
    description: 'Wellington\'s beloved St Patrick\'s Day celebration — a colourful parade through the city followed by a free festival on the waterfront with live Irish music, dancing, food and family entertainment. A fantastic free afternoon out for all ages.',
    url: 'https://www.eventfinda.co.nz/whatson/events/wellington',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Wellington_Harbour%2C_New_Zealand%2C_Nov._2009.jpg/960px-Wellington_Harbour%2C_New_Zealand%2C_Nov._2009.jpg',
    pick: true,
  
    label: '☘️ St Patrick\'s Day',
    labelStyle: 'color:#1A6A2A',
    stripStyle: 'background:linear-gradient(90deg,#1A6A2A,#2eaa44)',
    free: 'Free',
    family: 'All Ages',},
  {
    title: 'Zealandia — Eco Sanctuary',
    type: 'outdoor', day: 'sun', weekend: '2026-03-21', region: 'wellington',
    time: 'Daily 9:00 am – 5:00 pm (last entry 4:00 pm)',
    venue: '53 Waiapu Rd, Karori',
    description: 'A world-first urban eco-sanctuary where tuatara roam freely and kākā swoop overhead. Easy bush walks, a family-friendly visitor centre and one of Wellington\'s most remarkable experiences — genuinely unlike anywhere else in NZ.',
    url: 'https://www.visitzealandia.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/KaroriWildlifeSanctuary.jpg/960px-KaroriWildlifeSanctuary.jpg',
    pick: false,
  
    label: '🌿 Nature',
    labelStyle: 'color:#1A8A6E',
    ticketed: true,
    family: 'Family',
    cost: 'Family ticket available',},
  {
    title: 'NZ Blackcaps v South Africa — T20 International',
    type: 'outdoor', day: 'sun', weekend: '2026-03-21', region: 'wellington',
    time: 'Sunday 22 March · Check tickets for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'The Blackcaps take on South Africa in a T20 at Hnry Stadium. T20 is the most family-friendly cricket format — fast, exciting and done in about three hours. The stadium\'s covered stands and waterfront location make it a brilliant day out.',
    url: 'https://www.tickets.nzc.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Cricket_test_at_Basin_Reserve%2C_10-15_February_1978_%2824668812080%29.jpg/960px-Cricket_test_at_Basin_Reserve%2C_10-15_February_1978_%2824668812080%29.jpg',
    pick: true,
  
    label: '🏏 T20 International',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — tickets.nzc.nz',},
  {
    title: 'Boneface Brewing — Sunday Session',
    type: 'outdoor', day: 'sun', weekend: '2026-03-21', region: 'upper-hutt',
    time: 'Sunday from 12:00 pm',
    venue: 'Boneface Brewing, Upper Hutt',
    description: 'Upper Hutt\'s best kept secret — Boneface\'s family-friendly taproom with rotating food trucks and excellent craft beer. Kids are genuinely welcome and well catered for. A perfect Sunday afternoon combining a Hutt Valley drive with a great feed.',
    url: 'https://www.bonefacebrewing.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Oxbow_Collaboration_Part_1_%2833338778230%29.jpg/960px-Oxbow_Collaboration_Part_1_%2833338778230%29.jpg',
    pick: false,
  
    label: '🍺 Brewery',
    labelStyle: 'color:#C8901A',
    family: 'Family',},
  {
    title: 'Karaone Putiputi with The Tīwhas',
    type: 'culture', day: 'sat', weekend: '2026-03-21', region: 'wellington',
    time: 'Check website for time',
    venue: 'Te Matapihi ki te Ao Nui, Te Ngākau Civic Square, Wellington CBD',
    description: 'A Pride celebration at Wellington\'s newly reopened library — make flower crowns (karaone putiputi) and enjoy live performances by The Tīwhas girl group. A joyful, family-friendly afternoon. Free.',
    url: 'https://wellington.govt.nz/news-and-events/event-calendar',
    img: '',
    pick: false,

    label: '🌸 Pride · Family',
    labelStyle: 'color:#8b4bcc',
    free: 'Free',
    family: 'Family',},

  // ── 28–29 Mar 2026 ───────────────────────────────────────────────────────
  {
    title: 'CubaDupa 2026 — Free Street Festival',
    type: 'music', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Sat 28 & Sun 29 March · All day & evening',
    venue: 'Cuba Street & Cuba Quarter, Wellington CBD',
    description: 'NZ\'s largest outdoor arts and music festival — 12 stages, street theatre, LED dragons, Bollywood dancers, samba drummers, circus, food trucks and pop-up art. Completely free for the whole family.',
    url: 'https://www.cubadupa.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Free_Agents_Brass_Band_%40_CubaDupa%2C_March_25%2C_2018_%2839204825960%29.jpg/960px-Free_Agents_Brass_Band_%40_CubaDupa%2C_March_25%2C_2018_%2839204825960%29.jpg',
    pick: true,
  
    label: '🎪 Street Festival',
    labelStyle: 'color:#8A1A1A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Wellington Cable Car & Botanic Garden',
    type: 'outdoor', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Daily · open hours vary',
    venue: 'Cable Car, Kelburn, Wellington',
    description: 'Take the iconic cable car up to Kelburn, stroll the Botanic Garden and enjoy harbour views. Walk back down for free. A classic Wellington family outing any weekend.',
    url: 'https://www.wellingtoncablecar.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Wellington_Cable_Car_%2832655662511%29.jpg/960px-Wellington_Cable_Car_%2832655662511%29.jpg',
    pick: false,
  
    label: '🚡 Iconic',
    labelStyle: 'color:#1A8A6E',
    family: 'Family',
    cost: '$5–9 cable car · Garden free',},
  {
    title: 'Martinborough Village & Wine Trail',
    type: 'outdoor', day: 'sat', weekend: '2026-03-28', region: 'wairarapa',
    time: 'Daily · self-guided',
    venue: 'Martinborough Village, Wairarapa',
    description: 'Hire bikes and pedal between world-class pinot noir cellar doors around the charming village square. Kids love the ride — parents love the wine. A classic Wairarapa day trip, just over an hour from Wellington.',
    url: '',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/NZ-Martinborough.jpg/960px-NZ-Martinborough.jpg',
    pick: false,
  
    label: '🍷 Day Trip',
    labelStyle: 'color:#7A3B8A',
    stripStyle: 'background:linear-gradient(90deg,#7A3B8A,#b06acc)',
    family: 'Family',},
  {
    title: 'Greytown — NZ\'s Prettiest Victorian Village',
    type: 'outdoor', day: 'sat', weekend: '2026-03-28', region: 'wairarapa',
    time: 'Daily · self-guided',
    venue: 'Greytown, Wairarapa',
    description: 'Stroll the heritage main street, browse boutique shops, grab a flat white and picnic at Papawai. One of the loveliest day trips from Wellington — just over an hour through the Remutakas.',
    url: '',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Greytown_New_Zealand.jpg/960px-Greytown_New_Zealand.jpg',
    pick: false,
  
    label: '🏘 Village',
    labelStyle: 'color:#7A3B8A',
    stripStyle: 'background:linear-gradient(90deg,#7A3B8A,#b06acc)',
    free: 'Free to wander',
    family: 'Family',},
  {
    title: 'Hurricanes v Reds',
    type: 'outdoor', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'The Hurricanes host the Queensland Reds at Hnry Stadium. Wellington\'s home Super Rugby games are always a fantastic atmosphere — the stadium is compact and loud, and the Hurricanes have a history of playing high-octane attacking rugby. Great live sport alongside CubaDupa this weekend.',
    url: 'https://www.hurricanes.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/The_Chiefs_%28Waikato%29_v_The_Hurricanes_%28Wellington%29.jpg/960px-The_Chiefs_%28Waikato%29_v_The_Hurricanes_%28Wellington%29.jpg',
    pick: true,
  
    label: '🌀 Super Rugby',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — hurricanes.flicket.co.nz',},
  {
    title: 'Māoriland Film Festival 2026',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'kapiti',
    time: '24–28 March · 10:00 am – 10:00 pm daily',
    venue: 'Māoriland Hub, 68 Main Street, Ōtaki',
    description: 'The Southern Hemisphere\'s largest indigenous film festival — five days of indigenous cinema from around the world, including NZ premieres and special events. The 2026 theme is "light that reveals our legacies."',
    url: 'https://www.maorilandfilm.co.nz',
    img: '',
    pick: false,

    label: '🎬 Film Festival',
    labelStyle: 'color:#C8390A',
    cost: 'Ticketed — maorilandfilm.co.nz',
    family: 'Family',},
  {
    title: 'Pātaka Art + Museum — IHI & Ongo Exhibition Openings',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'porirua',
    time: '10:00 am – 5:00 pm · Opening events Sat 28 Mar',
    venue: 'Pātaka Art + Museum, cnr Norrie & Parumoana Streets, Porirua',
    description: 'Double exhibition opening at Pātaka — IHI explores inner force through three emerging Māori artists, while Ongo: (Re)sounding the Vā unpacks Pacific sound and space. Opening day includes a free walk-through and live performances. Free admission.',
    url: 'https://pataka.org.nz/whats-on/',
    img: '',
    pick: false,

    label: '🎨 Free Exhibition',
    labelStyle: 'color:#5B4A8A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'The Rocky Horror Show — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Sat 2:30 pm matinee & 7:30 pm · Sun 1:00 pm (final show)',
    venue: 'St James Theatre, 77–87 Courtenay Place, Wellington',
    description: 'The iconic stage musical returns to NZ for the first time in 15 years — direct from the UK with a West End cast. Sweet Transvestite, Time Warp, Dammit Janet. Dress-up warmly encouraged. Final weekend.',
    url: 'https://rockyhorror.co.nz',
    img: '',
    pick: false,

    label: '🎭 Musical Theatre',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed — rockyhorror.co.nz',},
  {
    title: 'Wellington City Orchestra — Louise Webster Violin Concerto',
    type: 'music', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: '3:00 pm – 4:45 pm',
    venue: 'St Andrew\'s on The Terrace, 30 The Terrace, Wellington',
    description: 'Conductor Justus Rozemond leads the orchestra with violinist Helene Pohl. Includes the NZ premiere of Louise Webster\'s violin concerto, Lili Boulanger, and Prokofiev\'s Romeo and Juliet Suite No. 2.',
    url: 'https://events.humanitix.com/wellington-city-orchestra-28-march-2026',
    img: '',
    pick: false,

    label: '🎻 Live Orchestra',
    labelStyle: 'color:#5B4A8A',
    cost: 'From $20 · Children free',},
  {
    title: 'Peach PRC — Wandering Spirit Tour',
    type: 'music', day: 'sat', weekend: '2026-03-28', region: 'wellington',
    time: 'Doors 7:00 pm · Peach PRC 9:15 pm',
    venue: 'Shed 6, 4 Queens Wharf, Wellington',
    description: 'Australian pop artist Peach PRC headlines her NZ debut — theatrical boundary-pushing pop with 230M+ streams. Support from Sydney artist Salty. Licensed all-ages show on the Wellington waterfront.',
    url: 'https://www.frontiertouring.com/peachprc',
    img: '',
    pick: false,

    label: '🎤 Live Music',
    labelStyle: 'color:#C8390A',
    cost: 'GA $79.90 · VIP $179.90',},
  {
    title: 'The Superlative Artistry of Japan — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-03-28', region: 'upper-hutt',
    time: 'Gallery hours — check website',
    venue: 'Whirinaki Whare Taonga, 836 Fergusson Drive, Upper Hutt',
    description: 'Free travelling exhibition by the Embassy of Japan — closing this weekend. Captures Japan\'s monozukuri (craft) spirit across traditional kogei, elaborate Meiji-era works, contemporary craft and food art. Free entry.',
    url: 'https://www.expressions.org.nz/exhibitions/current-exhibitions/',
    img: '',
    pick: false,

    label: '🇯🇵 Free Exhibition · Closing',
    labelStyle: 'color:#8A1A1A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Wellington Phoenix Women v Western Sydney Wanderers',
    type: 'outdoor', day: 'sun', weekend: '2026-03-28', region: 'porirua',
    time: '2:00 pm kick-off',
    venue: 'Porirua Park, Porirua',
    description: 'A-League Women fixture — the Phoenix host Western Sydney Wanderers at their Porirua home ground. Fast, skilful women\'s football in an intimate community stadium setting. Broadcast on Sky Open.',
    url: 'https://wellingtonphoenix.com/matches/',
    img: '',
    pick: false,

    label: '⚽ A-League Women',
    labelStyle: 'color:#FF6600',
    family: 'Family',
    cost: 'Ticketed',},

  // ── 4–5 Apr 2026 ─────────────────────────────────────────────────────────
  {
    title: 'Armageddon Expo Wellington 2026',
    type: 'festival', day: 'sat', weekend: '2026-04-04', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'TSB Arena, Wellington Waterfront',
    description: 'NZ\'s biggest pop culture event — gaming, anime, comics, cosplay competitions, celebrity meet-and-greets and esports. Guest headliners include Andy Serkis and Renee O\'Connor. Thousands of cosplayers roam the floor. A brilliant Easter weekend outing for kids and big kids alike.',
    url: 'https://www.armageddonexpo.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg/960px-LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg',
    pick: true,
  
    label: '🤖 Pop Culture Expo',
    labelStyle: 'color:#1A5C99',
    family: 'Family',
    cost: 'Ticketed · Family passes available',},
  {
    title: 'White Ferns v South Africa — 3rd ODI',
    type: 'outdoor', day: 'sat', weekend: '2026-04-04', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Basin Reserve, Wellington',
    description: 'The White Ferns face South Africa in the third One Day International at the iconic Basin Reserve. A fantastic live sport experience for families — Wellington\'s most beloved cricket ground with a great atmosphere on a long Easter weekend.',
    url: 'https://www.tickets.nzc.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Basin_Reserve_newzealand.jpg/960px-Basin_Reserve_newzealand.jpg',
    pick: false,
  
    label: '🏏 Women\'s Cricket',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Check Basin Reserve website for tickets',},
  {
    title: 'Armageddon Expo — Easter Sunday',
    type: 'festival', day: 'sun', weekend: '2026-04-04', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'TSB Arena, Wellington Waterfront',
    description: 'Day two of Armageddon — often quieter than Saturday with still-full programming. Great chance for a second pass through the show floor, catching any panels or meet-and-greets you missed. Sunday also tends to have the best cosplay of the weekend.',
    url: 'https://www.armageddonexpo.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg/960px-LBCC_2014_-_Loki_and_Friends_%2815239112498%29.jpg',
    pick: false,
  
    label: '🤖 Pop Culture Expo',
    labelStyle: 'color:#1A5C99',
    family: 'Family',
    cost: 'Ticketed · Family passes available',},
  {
    title: 'NZ Brass Band National Championships — A & B Grade Finals',
    type: 'culture', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'The pinnacle of New Zealand\'s brass band scene — A and B Grade bands from across the country compete at Michael Fowler Centre. Spectacular ensemble playing in a world-class concert hall. A surprisingly brilliant live music experience for families, with big sound and high drama.',
    url: 'https://www.nzbrass.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: false,
  
    label: '🎺 Live Music · Competition',
    labelStyle: 'color:#5B4A8A',
    family: 'Family',
    cost: 'Ticketed',},
  {
    title: 'The BIG Easter Weekend at Ngā Manu',
    type: 'kids', day: 'sat', weekend: '2026-04-04', region: 'kapiti',
    time: '3–6 April · 10:00 am – 5:00 pm daily',
    venue: 'Ngā Manu Nature Reserve, Kauri Road, Waikanae',
    description: 'Family Easter fun at Ngā Manu Nature Reserve — Easter egg hunts with $3,000 in prizes among native birds and wildlife. A magical long-weekend adventure in one of Kāpiti\'s finest wildlife sanctuaries.',
    url: 'https://www.ngamanu.org.nz',
    img: '',
    pick: false,

    label: '🐣 Easter · Family',
    labelStyle: 'color:#C8901A',
    family: 'Family',
    cost: 'Entry fee applies',},
  {
    title: 'Ōtaki Easter Market',
    type: 'market', day: 'sun', weekend: '2026-04-04', region: 'kapiti',
    time: '10:00 am – 2:00 pm',
    venue: 'State Highway 1, Ōtaki (opposite New World)',
    description: 'Special Easter edition of the popular outdoor Ōtaki market — local stallholders, fresh produce, crafts and Easter surprises. A great stop on the way north for the long weekend.',
    url: 'https://kapiticoast.govt.nz/explore-kapiti/things-to-do-in-kapiti/whats-on/events-in-kapiti/',
    img: '',
    pick: false,

    label: '🛒 Easter Market',
    labelStyle: 'color:#1A6B3A',
    free: 'Free entry',
    family: 'Family',},

  // ── 11–12 Apr 2026 ───────────────────────────────────────────────────────
  {
    title: 'Hurricanes v Blues',
    type: 'outdoor', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Massive Super Rugby rivalry match — the Hurricanes host the Blues at Hnry Stadium. Blues vs Hurricanes is always one of the most electric games of the season. Loud, packed, and brilliant live sport.',
    url: 'https://www.hurricanes.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Hurricanes_vs_Waratahs_2015.jpg/960px-Hurricanes_vs_Waratahs_2015.jpg',
    pick: true,
  
    label: '🌀 Super Rugby',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — hurricanes.flicket.co.nz',},
  {
    title: 'Autumn in the Botanic Garden',
    type: 'outdoor', day: 'sat', weekend: '2026-04-11', region: 'wellington',
    time: 'Daily · open hours',
    venue: 'Wellington Botanic Garden, Kelburn',
    description: 'April is one of the best months to visit the Botanic Garden — golden and red autumn leaves across the deciduous sections, warm afternoon light and quieter paths. The duck pond and fenced playground are still big hits with kids. Free to enter, easy to reach by cable car.',
    url: 'https://www.wellington.govt.nz/parks-recreation/botanic-garden',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Wellington_Botanical_Garden_10.jpg/960px-Wellington_Botanical_Garden_10.jpg',
    pick: false,
  
    label: '🌿 Autumn Walk',
    labelStyle: 'color:#1A8A6E',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Martinborough in Autumn — Wine Trail',
    type: 'outdoor', day: 'sun', weekend: '2026-04-11', region: 'wairarapa',
    time: 'Daily · self-guided',
    venue: 'Martinborough Village, Wairarapa',
    description: 'Autumn is magic in Martinborough — the pinot noir vineyards turn brilliant gold and red, making the bike ride between cellar doors even more scenic. The village is quieter than summer and the welcome at every cellar door is warm. A perfect long weekend Sunday escape.',
    url: '',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/NZ-Martinborough.jpg/960px-NZ-Martinborough.jpg',
    pick: false,
  
    label: '🍷 Day Trip',
    labelStyle: 'color:#7A3B8A',
    stripStyle: 'background:linear-gradient(90deg,#7A3B8A,#b06acc)',
    family: 'Family',},
  {
    title: 'Porirua Grand Traverse',
    type: 'outdoor', day: 'sun', weekend: '2026-04-11', region: 'porirua',
    time: 'Sunday 12 April · From 7:00 am',
    venue: 'Start/Finish: Kai Tahi Foodhall, 20 Parumoana St, Porirua',
    description: 'Wellington\'s biggest multisport festival — choose from a 9km fun run/walk to a full 58km challenge crossing Porirua Harbour, native bush, coastal farmland and hidden trails. Options for all ages and abilities.',
    url: 'https://poriruagrandtraverse.co.nz',
    img: '',
    pick: false,

    label: '🏃 Multisport Festival',
    labelStyle: 'color:#C8390A',
    family: 'Family',
    cost: 'Entry fee — poriruagrandtraverse.co.nz',},

  // ── 18–19 Apr 2026 ───────────────────────────────────────────────────────
  {
    title: 'Brewtown Beer Fest 2026',
    type: 'festival', day: 'sat', weekend: '2026-04-18', region: 'upper-hutt',
    time: '12:00 pm – 6:30 pm',
    venue: 'Brewtown, 16 Miro St, Upper Hutt',
    description: 'Annual craft beer festival at Brewtown Upper Hutt — local and guest breweries, live music and food in the open-air courtyard of Upper Hutt\'s thriving craft beer hub.',
    url: 'https://brewtown.co.nz/beerfest',
    img: '',
    pick: false,

    label: '🍺 Beer Festival',
    labelStyle: 'color:#C8901A',
    cost: 'Ticketed — brewtown.co.nz/beerfest',},
  {
    title: 'Wellington Saints v Manawatu Jets',
    type: 'outdoor', day: 'sun', weekend: '2026-04-11', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'TSB Arena, Wellington Waterfront',
    description: 'Wellington\'s beloved Saints host Manawatu Jets at TSB Arena in the Sal\'s NBL. Fast, high-energy basketball in a compact arena where every seat is close to the action. Saints games are brilliant family sport — loud, local and always entertaining.',
    url: 'https://www.salsbasketball.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/2019_NCAA_Men%27s_Basketball_Finals_Game_3_crowd.jpg/960px-2019_NCAA_Men%27s_Basketball_Finals_Game_3_crowd.jpg',
    pick: false,
  
    label: '🏀 Sal\'s NBL Basketball',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — saints.co.nz',},

  // ── 25–26 Apr 2026 (ANZAC long weekend) ─────────────────────────────────
  {
    title: 'Faultline Ultra — Wellington Trail Races',
    type: 'outdoor', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: 'Check schedule',
    venue: 'Wellington City Centre & Trail Networks',
    description: 'Epic multi-distance trail running through Wellington\'s best trail networks across the ANZAC long weekend. From a beginner-friendly 6km to a 100-mile monster. The finish line in the city centre is a great free spectator spot to cheer runners home.',
    url: 'https://www.faultlineultra.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Kilian.jpg',
    pick: false,
  
    label: '🏃 Trail Running',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Ticketed · Distances from 6km to 100 miles',},
  {
    title: 'Pūkaha National Wildlife Centre',
    type: 'outdoor', day: 'sat', weekend: '2026-04-18', region: 'wairarapa',
    time: 'Daily · check hours',
    venue: 'Pūkaha, Mount Bruce, Wairarapa',
    description: 'Home to kiwi, kākāpō, kōkako and New Zealand\'s only white kiwi. Set in a large native forest reserve, the autumn colours here are stunning. Combine with a stop at Clareville Bakery on the way home for the ultimate Wairarapa day trip.',
    url: 'https://www.pukaha.org.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/TeTuatahianui.jpg/960px-TeTuatahianui.jpg',
    pick: false,
  
    label: '🐦 Wildlife',
    labelStyle: 'color:#4A7A0A',
    stripStyle: 'background:linear-gradient(90deg,#5A8A1A,#88c440)',
    family: 'Family',
    cost: 'Adults $25 · Children $12',},
  {
    title: 'Days Bay to Eastbourne Coastal Walk',
    type: 'outdoor', day: 'sat', weekend: '2026-04-18', region: 'lower-hutt',
    time: 'Daily · self-guided',
    venue: 'Days Bay & Eastbourne, Wellington Harbour',
    description: 'Take the Eastbourne ferry from the Wellington waterfront, walk the beautiful harbour-edge path to Eastbourne village and back, then grab fish and chips on the Days Bay waterfront. One of the region\'s best family half-day adventures and stunning in autumn light.',
    url: '',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Days_Bay%2C_Wellington%2C_New_Zealand.jpg/960px-Days_Bay%2C_Wellington%2C_New_Zealand.jpg',
    pick: false,
  
    label: '🚶 Coastal Walk',
    labelStyle: 'color:#1A8A6E',
    free: 'Free',
    family: 'Family',},
  {
    title: 'Glow in the Dark Titiwai Tours — Wellington Botanic Garden',
    type: 'outdoor', day: 'sat', weekend: '2026-04-18', region: 'wellington',
    time: 'Evening — check website for tour times',
    venue: 'Wellington Botanic Garden, Tinakori Road, Thorndon',
    description: 'Guided after-dark walk through the Wellington Botanic Garden to spot glowworms (titiwai) in their natural habitat. A magical evening experience for the whole family. Runs April through September.',
    url: 'https://wellington.govt.nz/news-and-events/events-and-festivals',
    img: '',
    pick: false,

    label: '✨ Glow Worms · Evening',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Ticketed',},
  {
    title: 'ANZAC Day — Dawn Service & National Ceremony',
    type: 'other', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: '6:00 am dawn service, 11:00 am national ceremony',
    venue: 'Pukeahu, Wellington',
    description: 'Wellington hosts New Zealand\'s national ANZAC Day commemorations. The 6am dawn service at Pukeahu is a deeply moving experience. The 11am National Commemoration Service is broadcast live on TVNZ 1 and RNZ. Also: wreath laying at the Cenotaph, Lambton Quay at 9am. Free and open to all.',
    url: '',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Dawn_service_gnangarra_03.jpg/960px-Dawn_service_gnangarra_03.jpg',
    pick: false,
  
    label: '🌺 National Commemoration',
    labelStyle: 'color:#8A1A00',
    stripStyle: 'background:linear-gradient(90deg,#8A1A00,#c43030)',
    free: 'Free',},
  {
    title: 'Te Papa: Gallipoli — The Scale of Our War',
    type: 'culture', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: 'Daily · check hours',
    venue: 'Te Papa Tongarewa, Wellington',
    description: 'Weta Workshop\'s extraordinary Gallipoli exhibition presents the human story of the campaign through giant-scale figures and personal stories. Deeply moving and perfectly timed for ANZAC Day. Free entry. One of the most powerful museum experiences in New Zealand.',
    url: 'https://www.tepapa.govt.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg/960px-Museum_of_New_Zealand_Te_Papa_Tongarewa_unsaturated.jpg',
    pick: false,
  
    label: '🏛 Free Exhibition',
    labelStyle: 'color:#5B4A8A',
    free: 'Free',
    family: 'Family',},
  {
    title: 'NZ Warriors v Dolphins — ANZAC Day Match',
    type: 'outdoor', day: 'sat', weekend: '2026-04-25', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Wellington hosts the prestigious NRL ANZAC Round for the first time — a historic night with the Warriors facing the Dolphins, including a pre-game ANZAC ceremony. Only the fourth time the Warriors have played an ANZAC match on New Zealand soil. A brilliant way to finish ANZAC Day.',
    url: 'https://www.nrl.com.au',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Melbourne_Storm_vs_Dolphins%2C_NRL_2024_Round_25_at_AAMI_Park.jpg/960px-Melbourne_Storm_vs_Dolphins%2C_NRL_2024_Round_25_at_AAMI_Park.jpg',
    pick: true,
  
    label: '🏉 NRL ANZAC Round',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed',},
  {
    title: 'Faultline Ultra — Day Two',
    type: 'outdoor', day: 'sun', weekend: '2026-04-25', region: 'wellington',
    time: 'Check schedule',
    venue: 'Wellington City Centre & Trail Networks',
    description: 'The longer Faultline Ultra distances continue into Sunday — the 53km, 103km and 100-mile runners are still out on course. Head to the city-centre finish zone to cheer them across the line. Free to spectate.',
    url: 'https://www.faultlineultra.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Kilian.jpg',
    pick: false,
  
    label: '🏃 Trail Running',
    labelStyle: 'color:#1A6B3A',},

  // ── 2–3 May 2026 ─────────────────────────────────────────────────────────
  {
    title: 'Fat Freddy\'s Drop — Based On A True Story (21st Anniversary)',
    type: 'music', day: 'sat', weekend: '2026-05-02', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'Wellington\'s own Fat Freddy\'s Drop perform their landmark debut album in full — Aotearoa\'s longest-charting album (111 weeks in the NZ Top 40). Three consecutive nights in their home city, also a tribute to founding member Chris \'MU\' Faiumu. An unmissable moment for any Wellington music fan.',
    url: 'https://www.fatfreddysdrop.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Fat_Freddys_Drop_Group_Photo.jpg',
    pick: true,
  
    label: '🎸 Live Music · Wellington Icon',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed',},
  {
    title: 'Best Foods Comedy Festival Gala — Opening Night',
    type: 'culture', day: 'sat', weekend: '2026-05-02', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Q Theatre, Wellington',
    description: 'The annual Comedy Festival Gala brings together the best national and international comedians for a single highlight-reel night, hosted by Dai Henwood. The perfect way to sample the festival and decide which full shows to book. Always sells out fast.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: true,
  
    label: '😂 Comedy Gala',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed',},
  {
    title: 'Fat Freddy\'s Drop — Final Night',
    type: 'music', day: 'sun', weekend: '2026-05-02', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'The final night of Fat Freddy\'s Drop\'s three-night homecoming run. Third nights traditionally go hardest — the band relaxed, the crowd knowing every word, and the horns section at full power. A very special send-off for an iconic album.',
    url: 'https://www.fatfreddysdrop.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Fat_Freddys_Drop_Group_Photo.jpg',
    pick: true,
  
    label: '🎸 Live Music',
    labelStyle: 'color:#8A1A1A',
    cost: 'Ticketed',},
  {
    title: 'NZ International Comedy Festival — Weekend Shows',
    type: 'culture', day: 'sat', weekend: '2026-05-09', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'The NZ International Comedy Festival is in full swing — dozens of shows from local legends and international acts across Wellington venues all month. This weekend features Felicity Ward, David Correos and many more. Check the full programme to find your picks.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: false,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},

  // ── 9–10 May 2026 ────────────────────────────────────────────────────────
  {
    title: 'Mother\'s Day in Wellington — Spoil Her Properly',
    type: 'other', day: 'sun', weekend: '2026-05-09', region: 'wellington',
    time: 'Daily',
    venue: 'Wellington CBD & Waterfront',
    description: 'Mother\'s Day in Wellington — brunch at a waterfront café, a stroll along the city\'s spectacular harbourside, and the cable car ride up to the Botanic Garden. The city\'s cafés pull out all the stops. Book ahead for the popular spots on Te Aro and the waterfront.',
    url: '',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Wellington_Harbour%2C_New_Zealand%2C_Nov._2009.jpg/960px-Wellington_Harbour%2C_New_Zealand%2C_Nov._2009.jpg',
    pick: false,
  
    label: '💐 Mother\'s Day',
    labelStyle: 'color:#8A3A6A',
    family: 'Family',},
  {
    title: 'NZ International Comedy Festival — Sunday Shows',
    type: 'culture', day: 'sun', weekend: '2026-05-09', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'A Comedy Festival show makes a brilliant Mother\'s Day treat — plenty of matinée and evening options this Sunday. Sashi Perera: Pear Tree runs this weekend, along with Ben Knight and David Correos. Check the programme for family-appropriate options.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: false,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},

  // ── 16–17 May 2026 ───────────────────────────────────────────────────────
  {
    title: 'NZ International Comedy Festival — Final Fortnight',
    type: 'culture', day: 'sat', weekend: '2026-05-16', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'The Comedy Festival\'s final fortnight — shows are filling up and the best ones are often sold out by now, so book early. This weekend features David Correos, Elouise Eftos: APHRODITE, and Sashi Perera: Pear Tree among many others. Check the website for full listings.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: true,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},
  {
    title: 'Marlon Williams — Tā te Manawa Tour',
    type: 'music', day: 'sat', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'Marlon Williams and the Yarra Benders perform ahead of a planned sabbatical from the spotlight — this is billed as his last Kiwi tour for the foreseeable future. An extraordinary performer at his peak, playing his Wellington home crowd. Sold out but worth checking for resale tickets.',
    url: 'https://www.iticketpro.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/MichaelFowlerCentre.jpg/960px-MichaelFowlerCentre.jpg',
    pick: true,
  
    label: '🎤 Live Music · Farewell Tour',
    labelStyle: 'color:#8A1A1A',
    cost: 'Sold out — check resale',},
  {
    title: 'Zealandia — Twilight Wildlife Experience',
    type: 'outdoor', day: 'sat', weekend: '2026-05-16', region: 'wellington',
    time: 'Check schedule for tour times',
    venue: '53 Waiapu Rd, Karori',
    description: 'May is a brilliant time to visit Zealandia — the 500-acre predator-free sanctuary is home to kiwi, tuatara, kākā and rare waterfowl. Evening twilight tours give the best chance to spot kiwi in the wild. One of Wellington\'s most extraordinary experiences.',
    url: 'https://www.visitzealandia.com',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/KaroriWildlifeSanctuary.jpg/960px-KaroriWildlifeSanctuary.jpg',
    pick: false,
  
    label: '🌿 Winter Walk',
    labelStyle: 'color:#1A6B3A',
    family: 'Family',
    cost: 'Adults $21 · Children $10.50 · Twilight tours extra',},

  // ── 23–24 May 2026 ───────────────────────────────────────────────────────
  {
    title: 'NZ International Comedy Festival — Final Weekend',
    type: 'culture', day: 'sat', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for times',
    venue: 'Various Wellington venues',
    description: 'The very last weekend of the NZ International Comedy Festival — Saturday night shows are the final chance to catch any acts you haven\'t seen yet. Last-chance performances from the full line-up before the curtain falls for 2026.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/QTheatreComFest2015.JPG/960px-QTheatreComFest2015.JPG',
    pick: false,
  
    label: '😂 Comedy Festival',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed per show',},
  {
    title: 'Hurricanes v Highlanders',
    type: 'outdoor', day: 'sat', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Hnry Stadium, 105 Waterloo Quay, Wellington',
    description: 'Hurricanes host the Highlanders in what shapes up as a crucial Super Rugby fixture late in the season. Always a physical, passionate contest between two sides with proud rugby traditions. A great way to start a big Wellington weekend.',
    url: 'https://www.hurricanes.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Highlander_vs_Hurricanes_2005.jpg/960px-Highlander_vs_Hurricanes_2005.jpg',
    pick: false,
  
    label: '🌀 Super Rugby',
    labelStyle: 'color:#2478A8',
    family: 'Family',
    cost: 'Ticketed — hurricanes.flicket.co.nz',},
  {
    title: 'Eddie Izzard — The Remix: The First 35 Years',
    type: 'culture', day: 'sun', weekend: '2026-05-23', region: 'wellington',
    time: 'Check schedule for time',
    venue: 'Michael Fowler Centre, Wellington',
    description: 'Eddie Izzard closes out the NZ International Comedy Festival with a one-person show remixing and reimagining highlights from 35 years of sell-out shows — from 1993\'s The Ambassadors to 2019\'s Wunderbar. One of the great stand-up performers of a generation, live in Wellington.',
    url: 'https://www.comedytown.co.nz',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Eddie_Izzard_comes_to_Crouch_End.jpg/960px-Eddie_Izzard_comes_to_Crouch_End.jpg',
    pick: true,
  
    label: '😂 Comedy Festival · Closing Night',
    labelStyle: 'color:#5B4A8A',
    cost: 'Ticketed',},
];
